import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const root = process.cwd();
const put = (p, c) => {
  const full = join(root, p);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, c, 'utf8');
  console.log('  + ' + p);
};
const L = (a) => a.join('\n');

// ============================================================
// desktop/package.json
// ============================================================
put('desktop/package.json', JSON.stringify({
  name: 'school-ms-desktop',
  productName: 'School MS',
  version: '1.0.0',
  description: 'School Management System - Desktop',
  main: 'main.js',
  scripts: {
    start: 'electron .',
    dist: 'electron-builder --win --publish=never',
    'dist:portable': 'electron-builder --win portable --publish=never'
  },
  devDependencies: {
    'electron': '^31.0.0',
    'electron-builder': '^24.13.3'
  },
  dependencies: {
    'embedded-postgres': '^16.4.0-beta.15'
  }
}, null, 2) + '\n');

// ============================================================
// desktop/main.js — Electron entry point
// ============================================================
put('desktop/main.js', L([
  "const { app, BrowserWindow, dialog, shell } = require('electron');",
  "const { spawn, fork } = require('node:child_process');",
  "const { existsSync, mkdirSync, writeFileSync } = require('node:fs');",
  "const { join } = require('node:path');",
  "const path = require('node:path');",
  "",
  "const IS_DEV = !app.isPackaged;",
  "const USER_DATA = app.getPath('userData');",
  "const RESOURCES = app.isPackaged ? process.resourcesPath : join(__dirname, '..');",
  "",
  "const PG_PORT = 55432;",
  "const API_PORT = 4400;",
  "const WEB_PORT = 3300;",
  "",
  "const PGDATA = join(USER_DATA, 'pgdata');",
  "const UPLOADS = join(USER_DATA, 'uploads');",
  "const LOGS = join(USER_DATA, 'logs');",
  "",
  "[PGDATA, UPLOADS, LOGS].forEach((d) => { if (!existsSync(d)) mkdirSync(d, { recursive: true }); });",
  "",
  "let splash = null;",
  "let mainWindow = null;",
  "let pg = null;",
  "let apiProc = null;",
  "let webProc = null;",
  "",
  "// -------- Logging --------",
  "function log(name, msg) {",
  "  const line = '[' + new Date().toISOString() + '] ' + msg + '\\n';",
  "  try { require('node:fs').appendFileSync(join(LOGS, name + '.log'), line); } catch {}",
  "  process.stdout.write('[' + name + '] ' + msg + '\\n');",
  "}",
  "",
  "// -------- Splash screen --------",
  "function createSplash() {",
  "  splash = new BrowserWindow({",
  "    width: 400, height: 260,",
  "    frame: false, transparent: false,",
  "    resizable: false, alwaysOnTop: true,",
  "    webPreferences: { contextIsolation: true },",
  "  });",
  "  splash.loadFile(join(__dirname, 'splash.html'));",
  "}",
  "",
  "function setSplashStatus(status) {",
  "  if (splash && !splash.isDestroyed()) {",
  "    splash.webContents.executeJavaScript('window.setStatus(' + JSON.stringify(status) + ')').catch(() => {});",
  "  }",
  "}",
  "",
  "// -------- Postgres --------",
  "async function startPostgres() {",
  "  setSplashStatus('Starting database...');",
  "  log('main', 'Starting embedded Postgres on port ' + PG_PORT + ' with data ' + PGDATA);",
  "",
  "  const EmbeddedPostgres = require('embedded-postgres').default;",
  "",
  "  pg = new EmbeddedPostgres({",
  "    databaseDir: PGDATA,",
  "    user: 'school',",
  "    password: 'school',",
  "    port: PG_PORT,",
  "    persistent: true,",
  "  });",
  "",
  "  const alreadyInitialized = existsSync(join(PGDATA, 'PG_VERSION'));",
  "",
  "  if (!alreadyInitialized) {",
  "    log('main', 'First run — initializing Postgres cluster');",
  "    await pg.initialise();",
  "    await pg.start();",
  "    await pg.createDatabase('school_ms');",
  "    log('main', 'Database created');",
  "  } else {",
  "    log('main', 'Existing cluster — starting');",
  "    await pg.start();",
  "  }",
  "",
  "  log('main', 'Postgres is up');",
  "}",
  "",
  "// -------- Run migrations + seed --------",
  "async function migrateIfNeeded() {",
  "  setSplashStatus('Preparing database...');",
  "",
  "  const prismaCli = join(RESOURCES, 'app', 'packages', 'database', 'node_modules', 'prisma', 'build', 'index.js');",
  "  const schemaPath = join(RESOURCES, 'app', 'packages', 'database', 'prisma', 'schema.prisma');",
  "  const seedPath = join(RESOURCES, 'app', 'packages', 'database', 'prisma', 'seed.js');",
  "",
  "  const env = {",
  "    ...process.env,",
  "    DATABASE_URL: 'postgresql://school:school@localhost:' + PG_PORT + '/school_ms?schema=public',",
  "  };",
  "",
  "  // Migrate",
  "  if (existsSync(prismaCli) && existsSync(schemaPath)) {",
  "    log('main', 'Running prisma migrate deploy');",
  "    await runNode(prismaCli, ['migrate', 'deploy', '--schema', schemaPath], env, 'migrate');",
  "  } else {",
  "    log('main', 'Prisma CLI not found at ' + prismaCli);",
  "  }",
  "",
  "  // Seed (idempotent — safe to run every start)",
  "  if (existsSync(seedPath)) {",
  "    log('main', 'Running seed');",
  "    await runNode(seedPath, [], env, 'seed').catch((e) => log('main', 'Seed warning: ' + e.message));",
  "  }",
  "}",
  "",
  "function runNode(scriptPath, args, env, tag) {",
  "  return new Promise((resolve, reject) => {",
  "    const p = fork(scriptPath, args, { env, silent: true, execArgv: [] });",
  "    p.stdout?.on('data', (d) => log(tag, d.toString().trim()));",
  "    p.stderr?.on('data', (d) => log(tag + ':err', d.toString().trim()));",
  "    p.on('exit', (code) => code === 0 ? resolve() : reject(new Error(tag + ' exited ' + code)));",
  "    p.on('error', reject);",
  "    setTimeout(() => { try { p.kill(); } catch {} ; reject(new Error(tag + ' timeout')); }, 120000);",
  "  });",
  "}",
  "",
  "// -------- Spawn API --------",
  "async function startApi() {",
  "  setSplashStatus('Starting server...');",
  "  log('main', 'Starting API');",
  "",
  "  const apiEntry = join(RESOURCES, 'app', 'apps', 'api', 'dist', 'main.js');",
  "  if (!existsSync(apiEntry)) throw new Error('API entry missing: ' + apiEntry);",
  "",
  "  apiProc = spawn(process.execPath, [apiEntry], {",
  "    env: {",
  "      ...process.env,",
  "      ELECTRON_RUN_AS_NODE: '1',",
  "      NODE_ENV: 'production',",
  "      API_PORT: String(API_PORT),",
  "      DATABASE_URL: 'postgresql://school:school@localhost:' + PG_PORT + '/school_ms?schema=public',",
  "      JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET || 'desktop_jwt_access_' + 'x'.repeat(20),",
  "      JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET || 'desktop_jwt_refresh_' + 'x'.repeat(20),",
  "      JWT_ACCESS_TTL: '12h',",
  "      JWT_REFRESH_TTL: '30d',",
  "      UPLOAD_DIR: UPLOADS,",
  "    },",
  "    stdio: ['ignore', 'pipe', 'pipe'],",
  "  });",
  "",
  "  apiProc.stdout.on('data', (d) => log('api', d.toString().trim()));",
  "  apiProc.stderr.on('data', (d) => log('api:err', d.toString().trim()));",
  "  apiProc.on('exit', (code) => log('main', 'API exited with ' + code));",
  "",
  "  await waitForPort(API_PORT, 60000);",
  "  log('main', 'API up on ' + API_PORT);",
  "}",
  "",
  "// -------- Spawn Web --------",
  "async function startWeb() {",
  "  setSplashStatus('Starting interface...');",
  "  log('main', 'Starting Web');",
  "",
  "  const webEntry = join(RESOURCES, 'app', 'apps', 'web', '.next', 'standalone', 'apps', 'web', 'server.js');",
  "  const fallback = join(RESOURCES, 'app', 'apps', 'web', '.next', 'standalone', 'server.js');",
  "  const entry = existsSync(webEntry) ? webEntry : fallback;",
  "",
  "  if (!existsSync(entry)) throw new Error('Web entry missing. Looked at:\\n' + webEntry + '\\n' + fallback);",
  "",
  "  webProc = spawn(process.execPath, [entry], {",
  "    env: {",
  "      ...process.env,",
  "      ELECTRON_RUN_AS_NODE: '1',",
  "      NODE_ENV: 'production',",
  "      PORT: String(WEB_PORT),",
  "      HOSTNAME: '127.0.0.1',",
  "      API_INTERNAL_URL: 'http://127.0.0.1:' + API_PORT,",
  "      NEXT_PUBLIC_API_URL: 'http://127.0.0.1:' + API_PORT,",
  "    },",
  "    cwd: join(RESOURCES, 'app', 'apps', 'web'),",
  "    stdio: ['ignore', 'pipe', 'pipe'],",
  "  });",
  "",
  "  webProc.stdout.on('data', (d) => log('web', d.toString().trim()));",
  "  webProc.stderr.on('data', (d) => log('web:err', d.toString().trim()));",
  "  webProc.on('exit', (code) => log('main', 'Web exited with ' + code));",
  "",
  "  await waitForPort(WEB_PORT, 60000);",
  "  log('main', 'Web up on ' + WEB_PORT);",
  "}",
  "",
  "// -------- Port waiter --------",
  "function waitForPort(port, timeoutMs) {",
  "  return new Promise((resolve, reject) => {",
  "    const started = Date.now();",
  "    const net = require('node:net');",
  "    function tryOnce() {",
  "      const s = net.connect(port, '127.0.0.1');",
  "      s.on('connect', () => { s.destroy(); resolve(); });",
  "      s.on('error', () => {",
  "        s.destroy();",
  "        if (Date.now() - started > timeoutMs) return reject(new Error('Timeout waiting for port ' + port));",
  "        setTimeout(tryOnce, 500);",
  "      });",
  "    }",
  "    tryOnce();",
  "  });",
  "}",
  "",
  "// -------- Main window --------",
  "function createWindow() {",
  "  mainWindow = new BrowserWindow({",
  "    width: 1400, height: 900,",
  "    minWidth: 1000, minHeight: 700,",
  "    backgroundColor: '#f3f4f6',",
  "    show: false,",
  "    autoHideMenuBar: true,",
  "    webPreferences: { contextIsolation: true, nodeIntegration: false },",
  "  });",
  "",
  "  mainWindow.loadURL('http://127.0.0.1:' + WEB_PORT + '/fr/login');",
  "",
  "  mainWindow.once('ready-to-show', () => {",
  "    if (splash) splash.destroy();",
  "    mainWindow.show();",
  "  });",
  "",
  "  // External links open in the system browser",
  "  mainWindow.webContents.setWindowOpenHandler(({ url }) => {",
  "    shell.openExternal(url);",
  "    return { action: 'deny' };",
  "  });",
  "",
  "  mainWindow.on('closed', () => { mainWindow = null; });",
  "}",
  "",
  "// -------- Error screen --------",
  "function showError(err) {",
  "  log('main', 'FATAL: ' + (err?.stack || err?.message || String(err)));",
  "  if (splash) splash.destroy();",
  "  dialog.showErrorBox(",
  "    'School MS - Startup Failed',",
  "    'The application failed to start.\\n\\n' +",
  "    (err?.message || String(err)) + '\\n\\n' +",
  "    'Logs: ' + LOGS",
  "  );",
  "  app.quit();",
  "}",
  "",
  "// -------- Lifecycle --------",
  "app.whenReady().then(async () => {",
  "  createSplash();",
  "  try {",
  "    await startPostgres();",
  "    await migrateIfNeeded();",
  "    await startApi();",
  "    await startWeb();",
  "    createWindow();",
  "  } catch (e) {",
  "    showError(e);",
  "  }",
  "});",
  "",
  "app.on('window-all-closed', () => { app.quit(); });",
  "",
  "app.on('before-quit', async (e) => {",
  "  log('main', 'Shutting down...');",
  "  try { if (webProc) webProc.kill(); } catch {}",
  "  try { if (apiProc) apiProc.kill(); } catch {}",
  "  try { if (pg) await pg.stop(); } catch {}",
  "});",
  ""
]));

// ============================================================
// desktop/splash.html
// ============================================================
put('desktop/splash.html', L([
  "<!DOCTYPE html>",
  "<html>",
  "<head>",
  "<meta charset=\"utf-8\">",
  "<style>",
  "  body {",
  "    margin: 0; padding: 0;",
  "    font-family: -apple-system, 'Segoe UI', Roboto, sans-serif;",
  "    background: linear-gradient(135deg, #0f766e 0%, #0d6f6a 100%);",
  "    color: white;",
  "    display: flex; flex-direction: column;",
  "    align-items: center; justify-content: center;",
  "    height: 100vh; user-select: none; -webkit-app-region: drag;",
  "  }",
  "  .logo { font-size: 36px; font-weight: 700; letter-spacing: 2px; margin-bottom: 12px; }",
  "  .sub { font-size: 13px; opacity: 0.8; margin-bottom: 30px; }",
  "  .spinner {",
  "    width: 32px; height: 32px;",
  "    border: 3px solid rgba(255,255,255,0.25);",
  "    border-top-color: white;",
  "    border-radius: 50%;",
  "    animation: spin 0.9s linear infinite;",
  "    margin-bottom: 16px;",
  "  }",
  "  @keyframes spin { to { transform: rotate(360deg); } }",
  "  #status { font-size: 12px; opacity: 0.9; min-height: 18px; }",
  "  .version { position: absolute; bottom: 12px; font-size: 10px; opacity: 0.5; }",
  "</style>",
  "</head>",
  "<body>",
  "  <div class=\"logo\">School MS</div>",
  "  <div class=\"sub\">School Management System</div>",
  "  <div class=\"spinner\"></div>",
  "  <div id=\"status\">Starting...</div>",
  "  <div class=\"version\">v1.0.0</div>",
  "  <script>",
  "    window.setStatus = function(s) { document.getElementById('status').textContent = s; };",
  "  </script>",
  "</body>",
  "</html>",
  ""
]));

// ============================================================
// desktop/electron-builder.yml
// ============================================================
put('desktop/electron-builder.yml', L([
  "appId: cm.schoolms.desktop",
  "productName: School MS",
  "copyright: Copyright 2026 School MS",
  "",
  "directories:",
  "  output: dist",
  "  buildResources: build",
  "",
  "files:",
  "  - main.js",
  "  - splash.html",
  "  - package.json",
  "  - node_modules/**/*",
  "",
  "# Copy the built API + Web + Prisma into resources/app/",
  "extraResources:",
  "  - from: ../apps/api/dist",
  "    to: app/apps/api/dist",
  "  - from: ../apps/api/assets",
  "    to: app/apps/api/assets",
  "  - from: ../apps/web/.next/standalone",
  "    to: app/apps/web/.next/standalone",
  "  - from: ../apps/web/.next/static",
  "    to: app/apps/web/.next/static",
  "  - from: ../apps/web/public",
  "    to: app/apps/web/public",
  "  - from: ../packages/database/prisma",
  "    to: app/packages/database/prisma",
  "  - from: ../packages/database/dist",
  "    to: app/packages/database/dist",
  "  - from: ../packages/shared/dist",
  "    to: app/packages/shared/dist",
  "",
  "asar: true",
  "asarUnpack:",
  "  - '**/node_modules/embedded-postgres/**'",
  "  - '**/node_modules/@embedded-postgres/**'",
  "",
  "win:",
  "  target:",
  "    - target: nsis",
  "      arch: [x64]",
  "    - target: portable",
  "      arch: [x64]",
  "  icon: build/icon.ico",
  "  artifactName: ${productName}-${version}-${arch}.${ext}",
  "",
  "nsis:",
  "  oneClick: false",
  "  perMachine: false",
  "  allowToChangeInstallationDirectory: true",
  "  createDesktopShortcut: true",
  "  createStartMenuShortcut: true",
  "  shortcutName: School MS",
  ""
]));

console.log('\nOK create-desktop.mjs — files written to /desktop');
console.log('');
console.log('Next steps:');
console.log('  cd desktop');
console.log('  npm install');
console.log('  (this downloads embedded-postgres binaries ~80MB)');