import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const root = process.cwd();
const files = {};
const put = (p, c) => { files[p] = c; };

// ---------- shared schemas ----------
put('packages/shared/src/schemas/finance.ts', [
  "import { z } from 'zod';",
  "",
  "export const paymentMethods = ['CASH','MTN_MOMO','ORANGE_MONEY','BANK_TRANSFER','CHEQUE','CARD','OTHER'] as const;",
  "",
  "export const createFeeSchema = z.object({",
  "  name: z.string().min(1),",
  "  amount: z.number().int().positive(),",
  "  classId: z.string().optional(),",
  "  isActive: z.boolean().default(true),",
  "});",
  "",
  "export const createInvoiceSchema = z.object({",
  "  studentId: z.string().min(1),",
  "  dueDate: z.string(),",
  "  total: z.number().int().positive(),",
  "});",
  "",
  "export const recordPaymentSchema = z.object({",
  "  amount: z.number().int().positive(),",
  "  method: z.enum(paymentMethods),",
  "  reference: z.string().optional(),",
  "});",
  "",
  "export type CreateFeeDto = z.infer<typeof createFeeSchema>;",
  "export type CreateInvoiceDto = z.infer<typeof createInvoiceSchema>;",
  "export type RecordPaymentDto = z.infer<typeof recordPaymentSchema>;",
  ""
].join('\n'));

put('packages/shared/src/index.ts', [
  "export * from './schemas/auth';",
  "export * from './schemas/student';",
  "export * from './schemas/finance';",
  "export * from './constants';",
  ""
].join('\n'));

// ---------- finance service ----------
put('apps/api/src/finance/finance.service.ts', [
  "import { Injectable, NotFoundException, BadRequestException } from '@nestjs/common';",
  "import { PrismaService } from '../prisma/prisma.service';",
  "import { CreateInvoiceDto, RecordPaymentDto, CreateFeeDto } from '@school/shared';",
  "",
  "@Injectable()",
  "export class FinanceService {",
  "  constructor(private prisma: PrismaService) {}",
  "",
  "  listFees(schoolId: string) {",
  "    return this.prisma.fee.findMany({ where: { schoolId }, orderBy: { name: 'asc' } });",
  "  }",
  "",
  "  createFee(schoolId: string, dto: CreateFeeDto) {",
  "    return this.prisma.fee.create({ data: { schoolId, name: dto.name, amount: dto.amount, classId: dto.classId ?? null, isActive: dto.isActive ?? true } });",
  "  }",
  "",
  "  listInvoices(schoolId: string) {",
  "    return this.prisma.invoice.findMany({",
  "      where: { schoolId },",
  "      include: { student: { select: { id: true, firstName: true, lastName: true, admissionNo: true } } },",
  "      orderBy: { issuedDate: 'desc' },",
  "      take: 200,",
  "    });",
  "  }",
  "",
  "  async getInvoice(id: string) {",
  "    const inv = await this.prisma.invoice.findUnique({",
  "      where: { id },",
  "      include: { student: true },",
  "    });",
  "    if (!inv) throw new NotFoundException('invoice_not_found');",
  "    const payments = await this.prisma.payment.findMany({",
  "      where: { invoiceId: id },",
  "      orderBy: { paidAt: 'desc' },",
  "    });",
  "    return { ...inv, payments };",
  "  }",
  "",
  "  async createInvoice(schoolId: string, dto: CreateInvoiceDto) {",
  "    const year = new Date().getFullYear();",
  "    const prefix = 'INV-' + year + '-';",
  "    const last = await this.prisma.invoice.findFirst({",
  "      where: { schoolId, invoiceNo: { startsWith: prefix } },",
  "      orderBy: { invoiceNo: 'desc' },",
  "    });",
  "    const n = last ? parseInt(last.invoiceNo.slice(prefix.length), 10) + 1 : 1;",
  "    const invoiceNo = prefix + String(n).padStart(5, '0');",
  "    return this.prisma.invoice.create({",
  "      data: {",
  "        schoolId,",
  "        studentId: dto.studentId,",
  "        invoiceNo,",
  "        dueDate: new Date(dto.dueDate),",
  "        total: dto.total,",
  "        amountPaid: 0,",
  "        balance: dto.total,",
  "        status: 'UNPAID',",
  "      },",
  "    });",
  "  }",
  "",
  "  async recordPayment(schoolId: string, invoiceId: string, dto: RecordPaymentDto) {",
  "    const inv = await this.prisma.invoice.findUnique({ where: { id: invoiceId } });",
  "    if (!inv) throw new NotFoundException('invoice_not_found');",
  "    if (dto.amount > inv.balance) throw new BadRequestException('amount_exceeds_balance');",
  "    const newPaid = inv.amountPaid + dto.amount;",
  "    const newBalance = inv.total - newPaid;",
  "    const newStatus = newBalance <= 0 ? 'PAID' : newPaid > 0 ? 'PARTIAL' : 'UNPAID';",
  "    const results = await this.prisma.$transaction([",
  "      this.prisma.payment.create({",
  "        data: {",
  "          schoolId, invoiceId, studentId: inv.studentId,",
  "          amount: dto.amount, method: dto.method,",
  "          reference: dto.reference ?? null, status: 'SUCCESS',",
  "        },",
  "      }),",
  "      this.prisma.invoice.update({",
  "        where: { id: invoiceId },",
  "        data: { amountPaid: newPaid, balance: newBalance, status: newStatus },",
  "      }),",
  "    ]);",
  "    return results[0];",
  "  }",
  "",
  "  async getSummary(schoolId: string) {",
  "    const billed = await this.prisma.invoice.aggregate({ where: { schoolId }, _sum: { total: true } });",
  "    const collected = await this.prisma.payment.aggregate({ where: { schoolId }, _sum: { amount: true } });",
  "    const outstanding = await this.prisma.invoice.aggregate({ where: { schoolId, status: { not: 'PAID' } }, _sum: { balance: true } });",
  "    const count = await this.prisma.invoice.count({ where: { schoolId } });",
  "    return {",
  "      currency: 'XAF',",
  "      totalBilled: billed._sum.total ?? 0,",
  "      totalCollected: collected._sum.amount ?? 0,",
  "      totalOutstanding: outstanding._sum.balance ?? 0,",
  "      invoiceCount: count,",
  "    };",
  "  }",
  "}",
  ""
].join('\n'));

// ---------- finance controller ----------
put('apps/api/src/finance/finance.controller.ts', [
  "import { Body, Controller, Get, Param, Post, Req, UseGuards } from '@nestjs/common';",
  "import { FinanceService } from './finance.service';",
  "import { JwtAuthGuard } from '../common/guards/jwt-auth.guard';",
  "import { ZodValidationPipe } from '../common/pipes/zod.pipe';",
  "import {",
  "  createFeeSchema, createInvoiceSchema, recordPaymentSchema,",
  "  CreateFeeDto, CreateInvoiceDto, RecordPaymentDto,",
  "} from '@school/shared';",
  "",
  "@UseGuards(JwtAuthGuard)",
  "@Controller('finance')",
  "export class FinanceController {",
  "  constructor(private svc: FinanceService) {}",
  "",
  "  @Get('summary')",
  "  summary(@Req() req: any) { return this.svc.getSummary(req.user.schoolId); }",
  "",
  "  @Get('fees')",
  "  listFees(@Req() req: any) { return this.svc.listFees(req.user.schoolId); }",
  "",
  "  @Post('fees')",
  "  createFee(@Req() req: any, @Body(new ZodValidationPipe(createFeeSchema)) dto: CreateFeeDto) {",
  "    return this.svc.createFee(req.user.schoolId, dto);",
  "  }",
  "",
  "  @Get('invoices')",
  "  listInvoices(@Req() req: any) { return this.svc.listInvoices(req.user.schoolId); }",
  "",
  "  @Get('invoices/:id')",
  "  getInvoice(@Param('id') id: string) { return this.svc.getInvoice(id); }",
  "",
  "  @Post('invoices')",
  "  createInvoice(@Req() req: any, @Body(new ZodValidationPipe(createInvoiceSchema)) dto: CreateInvoiceDto) {",
  "    return this.svc.createInvoice(req.user.schoolId, dto);",
  "  }",
  "",
  "  @Post('invoices/:id/payments')",
  "  recordPayment(",
  "    @Req() req: any,",
  "    @Param('id') invoiceId: string,",
  "    @Body(new ZodValidationPipe(recordPaymentSchema)) dto: RecordPaymentDto,",
  "  ) {",
  "    return this.svc.recordPayment(req.user.schoolId, invoiceId, dto);",
  "  }",
  "}",
  ""
].join('\n'));

// ---------- finance module ----------
put('apps/api/src/finance/finance.module.ts', [
  "import { Module } from '@nestjs/common';",
  "import { FinanceService } from './finance.service';",
  "import { FinanceController } from './finance.controller';",
  "",
  "@Module({",
  "  providers: [FinanceService],",
  "  controllers: [FinanceController],",
  "})",
  "export class FinanceModule {}",
  ""
].join('\n'));

// ---------- app.module with FinanceModule registered ----------
put('apps/api/src/app.module.ts', [
  "import { Module } from '@nestjs/common';",
  "import { ConfigModule } from '@nestjs/config';",
  "import { PrismaModule } from './prisma/prisma.module';",
  "import { AuthModule } from './auth/auth.module';",
  "import { StudentsModule } from './students/students.module';",
  "import { FinanceModule } from './finance/finance.module';",
  "",
  "@Module({",
  "  imports: [",
  "    ConfigModule.forRoot({ isGlobal: true, envFilePath: ['.env', '../../.env'] }),",
  "    PrismaModule,",
  "    AuthModule,",
  "    StudentsModule,",
  "    FinanceModule,",
  "  ],",
  "})",
  "export class AppModule {}",
  ""
].join('\n'));

let n = 0;
for (const [rel, content] of Object.entries(files)) {
  const full = join(root, rel);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, content, 'utf8');
  n++;
  console.log('  + ' + rel);
}
console.log('\n✅ Finance backend: ' + n + ' files written');