import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const root = process.cwd();
const put = (p, c) => {
  const full = join(root, p);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, c, 'utf8');
  console.log('  + ' + p);
};
const L = (a) => a.join('\n');

// ============ PAYROLL PAGE ============
put('apps/web/app/[locale]/dashboard/payroll/page.tsx', L([
  "'use client';",
  "import { useEffect, useState } from 'react';",
  "import { apiFetch } from '@/lib/api';",
  "import { formatXAF } from '@/lib/format';",
  "",
  "const MONTHS_FR = ['Janvier','Fevrier','Mars','Avril','Mai','Juin','Juillet','Aout','Septembre','Octobre','Novembre','Decembre'];",
  "",
  "export default function PayrollPage() {",
  "  const now = new Date();",
  "  const [year, setYear] = useState(now.getFullYear());",
  "  const [month, setMonth] = useState(now.getMonth() + 1);",
  "  const [items, setItems] = useState<any[]>([]);",
  "  const [err, setErr] = useState<string | null>(null);",
  "  const [ok, setOk] = useState<string | null>(null);",
  "  const [generating, setGenerating] = useState(false);",
  "",
  "  const load = () => {",
  "    setErr(null);",
  "    apiFetch('/api/v1/payroll?year=' + year + '&month=' + month)",
  "      .then((r) => r.ok ? r.json() : [])",
  "      .then((d) => setItems(Array.isArray(d) ? d : []))",
  "      .catch((e) => setErr(String(e)));",
  "  };",
  "  useEffect(load, [year, month]);",
  "",
  "  const generate = async () => {",
  "    if (!confirm('Generer la paie pour ' + MONTHS_FR[month - 1] + ' ' + year + ' ?')) return;",
  "    setGenerating(true); setErr(null); setOk(null);",
  "    try {",
  "      const r = await apiFetch('/api/v1/payroll/generate', {",
  "        method: 'POST',",
  "        body: JSON.stringify({ year, month }),",
  "      });",
  "      if (!r.ok) {",
  "        const txt = await r.text();",
  "        if (txt.includes('payroll_already_generated')) { setErr('Paie deja generee pour ce mois.'); setGenerating(false); return; }",
  "        if (txt.includes('no_active_staff')) { setErr('Aucun personnel actif.'); setGenerating(false); return; }",
  "        throw new Error(txt);",
  "      }",
  "      const result = await r.json();",
  "      setOk(result.created + ' bulletins crees. Total: ' + formatXAF(result.total));",
  "      load();",
  "    } catch (e: any) { setErr(String(e)); }",
  "    finally { setGenerating(false); }",
  "  };",
  "",
  "  const payAll = async () => {",
  "    if (!confirm('Marquer tous les bulletins comme payes ?')) return;",
  "    await apiFetch('/api/v1/payroll/pay-all', { method: 'POST', body: JSON.stringify({ year, month }) });",
  "    load();",
  "  };",
  "",
  "  const payOne = async (id: string) => {",
  "    await apiFetch('/api/v1/payroll/' + id + '/pay', { method: 'POST' });",
  "    load();",
  "  };",
  "",
  "  const updateDeduction = async (id: string, deductions: number) => {",
  "    await apiFetch('/api/v1/payroll/' + id, { method: 'PUT', body: JSON.stringify({ deductions }) });",
  "    load();",
  "  };",
  "",
  "  const remove = async (id: string) => {",
  "    if (!confirm('Supprimer ce bulletin ?')) return;",
  "    await apiFetch('/api/v1/payroll/' + id, { method: 'DELETE' });",
  "    load();",
  "  };",
  "",
  "  const totalNet = items.reduce((a, i) => a + i.netPay, 0);",
  "  const totalPaid = items.filter((i) => i.paidAt).reduce((a, i) => a + i.netPay, 0);",
  "  const totalPending = totalNet - totalPaid;",
  "",
  "  return (",
  "    <div>",
  "      <div className=\"flex flex-wrap items-center justify-between gap-3\">",
  "        <h1 className=\"text-2xl font-bold\">Paie</h1>",
  "        <div className=\"flex flex-wrap items-center gap-2\">",
  "          <select value={month} onChange={(e) => setMonth(Number(e.target.value))} className=\"rounded border px-3 py-2 text-sm\">",
  "            {MONTHS_FR.map((m, i) => <option key={i} value={i + 1}>{m}</option>)}",
  "          </select>",
  "          <input type=\"number\" value={year} onChange={(e) => setYear(Number(e.target.value))}",
  "                 className=\"w-24 rounded border px-3 py-2 text-sm\" />",
  "          {items.length === 0 && (",
  "            <button onClick={generate} disabled={generating}",
  "                    className=\"rounded-lg bg-brand-600 px-4 py-2 text-sm text-white hover:bg-brand-700 disabled:opacity-50\">",
  "              {generating ? '…' : 'Generer la paie' }",
  "            </button>",
  "          )}",
  "          {items.length > 0 && totalPending > 0 && (",
  "            <button onClick={payAll}",
  "                    className=\"rounded-lg bg-green-600 px-4 py-2 text-sm text-white hover:bg-green-700\">",
  "              Tout marquer paye",
  "            </button>",
  "          )}",
  "        </div>",
  "      </div>",
  "",
  "      {err && <p className=\"mt-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800\">{err}</p>}",
  "      {ok && <p className=\"mt-4 rounded border border-green-200 bg-green-50 p-3 text-sm text-green-800\">{ok}</p>}",
  "",
  "      {items.length > 0 && (",
  "        <div className=\"mt-6 grid grid-cols-1 gap-4 sm:grid-cols-3\">",
  "          <div className=\"rounded-xl border border-teal-200 bg-teal-50 p-4\">",
  "            <div className=\"text-xs uppercase text-teal-800 opacity-70\">Total a payer</div>",
  "            <div className=\"mt-1 text-2xl font-bold text-teal-900\">{formatXAF(totalNet)}</div>",
  "          </div>",
  "          <div className=\"rounded-xl border border-green-200 bg-green-50 p-4\">",
  "            <div className=\"text-xs uppercase text-green-800 opacity-70\">Deja paye</div>",
  "            <div className=\"mt-1 text-2xl font-bold text-green-900\">{formatXAF(totalPaid)}</div>",
  "          </div>",
  "          <div className=\"rounded-xl border border-red-200 bg-red-50 p-4\">",
  "            <div className=\"text-xs uppercase text-red-800 opacity-70\">En attente</div>",
  "            <div className=\"mt-1 text-2xl font-bold text-red-900\">{formatXAF(totalPending)}</div>",
  "          </div>",
  "        </div>",
  "      )}",
  "",
  "      {items.length === 0 && !err && (",
  "        <p className=\"mt-8 rounded-lg border bg-white p-8 text-center text-gray-500\">",
  "          Aucun bulletin pour {MONTHS_FR[month - 1]} {year}. Cliquez sur <strong>Generer la paie</strong> pour creer les bulletins a partir des salaires de base.",
  "        </p>",
  "      )}",
  "",
  "      {items.length > 0 && (",
  "        <div className=\"mt-6 overflow-x-auto rounded-lg border bg-white\">",
  "          <table className=\"w-full border-collapse text-sm\">",
  "            <thead className=\"bg-gray-50 text-left\">",
  "              <tr>",
  "                <th className=\"p-3 font-medium\">Matricule</th>",
  "                <th className=\"p-3 font-medium\">Nom</th>",
  "                <th className=\"p-3 font-medium\">Poste</th>",
  "                <th className=\"p-3 text-right font-medium\">Brut</th>",
  "                <th className=\"p-3 text-right font-medium\">Retenues</th>",
  "                <th className=\"p-3 text-right font-medium\">Net a payer</th>",
  "                <th className=\"p-3 font-medium\">Statut</th>",
  "                <th className=\"p-3\"></th>",
  "              </tr>",
  "            </thead>",
  "            <tbody>",
  "              {items.map((it) => (",
  "                <tr key={it.id} className=\"border-t hover:bg-gray-50\">",
  "                  <td className=\"p-3 font-mono text-xs\">{it.staff.employeeNo}</td>",
  "                  <td className=\"p-3 font-medium\">{it.staff.firstName} {it.staff.lastName}</td>",
  "                  <td className=\"p-3 text-xs text-gray-600\">{it.staff.position}</td>",
  "                  <td className=\"p-3 text-right\">{formatXAF(it.grossPay)}</td>",
  "                  <td className=\"p-3 text-right\">",
  "                    <input type=\"number\" min={0} value={it.deductions}",
  "                           onChange={(e) => updateDeduction(it.id, Number(e.target.value))}",
  "                           className=\"w-24 rounded border px-2 py-1 text-right text-xs\" />",
  "                  </td>",
  "                  <td className=\"p-3 text-right font-bold text-teal-700\">{formatXAF(it.netPay)}</td>",
  "                  <td className=\"p-3\">",
  "                    <span className={'rounded-full px-2 py-0.5 text-xs font-medium ' +",
  "                      (it.paidAt ? 'bg-green-100 text-green-800' : 'bg-yellow-100 text-yellow-800')}>",
  "                      {it.paidAt ? 'Paye' : 'En attente'}",
  "                    </span>",
  "                  </td>",
  "                  <td className=\"p-3 text-right whitespace-nowrap\">",
  "                    {!it.paidAt && (",
  "                      <button onClick={() => payOne(it.id)} className=\"rounded bg-brand-600 px-3 py-1 text-xs text-white hover:bg-brand-700\">Payer</button>",
  "                    )}",
  "                    <button onClick={() => remove(it.id)} className=\"ml-2 rounded border border-red-300 px-2 py-1 text-xs text-red-700 hover:bg-red-50\">✕</button>",
  "                  </td>",
  "                </tr>",
  "              ))}",
  "            </tbody>",
  "          </table>",
  "        </div>",
  "      )}",
  "    </div>",
  "  );",
  "}",
  ""
]));

// ============ BULK IMPORT PAGE ============
put('apps/web/app/[locale]/dashboard/import/page.tsx', L([
  "'use client';",
  "import { useState } from 'react';",
  "import { apiFetch } from '@/lib/api';",
  "",
  "type Row = {",
  "  admissionNo?: string;",
  "  firstName: string;",
  "  lastName: string;",
  "  gender?: string;",
  "  dateOfBirth?: string;",
  "  className?: string;",
  "  guardianFirstName?: string;",
  "  guardianLastName?: string;",
  "  guardianPhone?: string;",
  "  guardianRelation?: string;",
  "  phone?: string;",
  "  email?: string;",
  "};",
  "",
  "export default function ImportPage() {",
  "  const [tab, setTab] = useState<'students' | 'parents'>('students');",
  "  const [csv, setCsv] = useState('');",
  "  const [rows, setRows] = useState<Row[]>([]);",
  "  const [preview, setPreview] = useState<any[]>([]);",
  "  const [result, setResult] = useState<any>(null);",
  "  const [parentResult, setParentResult] = useState<any>(null);",
  "  const [err, setErr] = useState<string | null>(null);",
  "  const [busy, setBusy] = useState(false);",
  "",
  "  const SAMPLE = 'admissionNo,firstName,lastName,gender,dateOfBirth,className,guardianFirstName,guardianLastName,guardianPhone,guardianRelation' + '\\n' +",
  "    'LBY-2026-0001,Aminata,Nkolo,FEMALE,2012-05-14,6eme A,Jean,Atangana,+237699112233,Pere' + '\\n' +",
  "    'LBY-2026-0002,Brice,Manga,MALE,2011-03-08,5eme A,Claudine,Mvogo,+237699445566,Mere';",
  "",
  "  const parseCsv = (text: string): Row[] => {",
  "    const lines = text.trim().split(/\\r?\\n/).filter((l) => l.trim());",
  "    if (lines.length < 2) return [];",
  "    const header = lines[0].split(',').map((h) => h.trim());",
  "    return lines.slice(1).map((line) => {",
  "      const cells = line.split(',').map((c) => c.trim());",
  "      const obj: any = {};",
  "      header.forEach((h, i) => { obj[h] = cells[i] || undefined; });",
  "      return obj as Row;",
  "    });",
  "  };",
  "",
  "  const onFile = (e: React.ChangeEvent<HTMLInputElement>) => {",
  "    const f = e.target.files?.[0];",
  "    if (!f) return;",
  "    const reader = new FileReader();",
  "    reader.onload = (ev) => setCsv(String(ev.target?.result || ''));",
  "    reader.readAsText(f);",
  "  };",
  "",
  "  const doPreview = async () => {",
  "    setErr(null); setPreview([]); setResult(null);",
  "    const r = parseCsv(csv);",
  "    if (r.length === 0) { setErr('CSV vide ou invalide.'); return; }",
  "    setRows(r);",
  "    const res = await apiFetch('/api/v1/bulk-import/students/preview', {",
  "      method: 'POST', body: JSON.stringify({ rows: r }),",
  "    });",
  "    if (!res.ok) { setErr(await res.text()); return; }",
  "    const d = await res.json();",
  "    setPreview(Array.isArray(d) ? d : []);",
  "  };",
  "",
  "  const doImport = async () => {",
  "    if (rows.length === 0) { setErr('Faites d abord un apercu.'); return; }",
  "    if (!confirm('Importer ' + rows.length + ' eleves ?')) return;",
  "    setBusy(true); setErr(null);",
  "    try {",
  "      const res = await apiFetch('/api/v1/bulk-import/students', {",
  "        method: 'POST', body: JSON.stringify({ rows }),",
  "      });",
  "      if (!res.ok) throw new Error(await res.text());",
  "      setResult(await res.json());",
  "      setPreview([]);",
  "    } catch (e: any) { setErr(String(e)); }",
  "    finally { setBusy(false); }",
  "  };",
  "",
  "  const generateParents = async () => {",
  "    if (!confirm('Creer un compte de connexion pour chaque parent qui n en a pas ?')) return;",
  "    setBusy(true); setErr(null); setParentResult(null);",
  "    try {",
  "      const res = await apiFetch('/api/v1/bulk-import/parents/generate', { method: 'POST' });",
  "      if (!res.ok) throw new Error(await res.text());",
  "      setParentResult(await res.json());",
  "    } catch (e: any) { setErr(String(e)); }",
  "    finally { setBusy(false); }",
  "  };",
  "",
  "  const downloadCsv = () => {",
  "    const blob = new Blob([parentResult.generated.map((g: any) => g.guardian + ',' + g.email + ',' + g.password + ',' + g.childCount).join('\\n')],",
  "      { type: 'text/csv' });",
  "    const url = URL.createObjectURL(blob);",
  "    const a = document.createElement('a');",
  "    a.href = url; a.download = 'parent-accounts.csv'; a.click();",
  "    URL.revokeObjectURL(url);",
  "  };",
  "",
  "  return (",
  "    <div>",
  "      <h1 className=\"text-2xl font-bold\">Import en masse</h1>",
  "      <p className=\"mt-1 text-sm text-gray-500\">Importer des eleves depuis un CSV, ou generer les comptes parents en un clic.</p>",
  "",
  "      <div className=\"mt-6 flex gap-2 border-b\">",
  "        <button onClick={() => setTab('students')} className={'border-b-2 px-4 py-2 text-sm ' + (tab === 'students' ? 'border-brand-600 font-medium text-brand-700' : 'border-transparent text-gray-600')}>Eleves (CSV)</button>",
  "        <button onClick={() => setTab('parents')} className={'border-b-2 px-4 py-2 text-sm ' + (tab === 'parents' ? 'border-brand-600 font-medium text-brand-700' : 'border-transparent text-gray-600')}>Comptes parents</button>",
  "      </div>",
  "",
  "      {err && <p className=\"mt-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800\">{err}</p>}",
  "",
  "      {tab === 'students' && (",
  "        <div className=\"mt-6 space-y-4\">",
  "          <div className=\"rounded-lg border bg-white p-5\">",
  "            <h2 className=\"font-semibold\">1. Charger le CSV</h2>",
  "            <p className=\"mt-1 text-xs text-gray-500\">Colonnes: admissionNo, firstName, lastName, gender, dateOfBirth, className, guardianFirstName, guardianLastName, guardianPhone, guardianRelation</p>",
  "            <div className=\"mt-3 flex flex-wrap items-center gap-2\">",
  "              <input type=\"file\" accept=\".csv,.txt\" onChange={onFile} className=\"text-sm\" />",
  "              <button onClick={() => setCsv(SAMPLE)} className=\"rounded border px-3 py-1 text-xs hover:bg-gray-50\">Exemple</button>",
  "            </div>",
  "            <textarea value={csv} onChange={(e) => setCsv(e.target.value)} rows={6}",
  "                      placeholder=\"Collez le CSV ici…\"",
  "                      className=\"mt-3 w-full rounded border px-3 py-2 font-mono text-xs\" />",
  "            <div className=\"mt-3 flex gap-2\">",
  "              <button onClick={doPreview} disabled={!csv.trim()}",
  "                      className=\"rounded bg-brand-600 px-4 py-2 text-sm text-white hover:bg-brand-700 disabled:opacity-50\">Apercu</button>",
  "              {preview.length > 0 && preview.every((p) => p.willCreate) && (",
  "                <button onClick={doImport} disabled={busy}",
  "                        className=\"rounded bg-green-600 px-4 py-2 text-sm text-white hover:bg-green-700 disabled:opacity-50\">",
  "                  {busy ? '…' : 'Importer ' + rows.length + ' eleves'}",
  "                </button>",
  "              )}",
  "            </div>",
  "          </div>",
  "",
  "          {preview.length > 0 && (",
  "            <div className=\"rounded-lg border bg-white p-5\">",
  "              <h2 className=\"font-semibold\">2. Apercu ({preview.length} lignes)</h2>",
  "              <div className=\"mt-3 max-h-96 overflow-y-auto\">",
  "                <table className=\"w-full border-collapse text-xs\">",
  "                  <thead className=\"bg-gray-50 text-left\">",
  "                    <tr>",
  "                      <th className=\"p-2\">#</th>",
  "                      <th className=\"p-2\">Nom</th>",
  "                      <th className=\"p-2\">Classe</th>",
  "                      <th className=\"p-2\">Statut</th>",
  "                    </tr>",
  "                  </thead>",
  "                  <tbody>",
  "                    {preview.slice(0, 100).map((p: any) => (",
  "                      <tr key={p.row} className='border-t'>",
  "                        <td className=\"p-2\">{p.row}</td>",
  "                        <td className=\"p-2\">{p.input.firstName} {p.input.lastName}</td>",
  "                        <td className=\"p-2\">{p.input.className || '—'}</td>",
  "                        <td className=\"p-2\">",
  "                          {p.willCreate",
  "                            ? <span className=\"text-green-700\">OK</span>",
  "                            : <span className=\"text-red-600\">{p.issues.join('; ')}</span>}",
  "                        </td>",
  "                      </tr>",
  "                    ))}",
  "                  </tbody>",
  "                </table>",
  "              </div>",
  "            </div>",
  "          )}",
  "",
  "          {result && (",
  "            <div className=\"rounded-lg border border-green-200 bg-green-50 p-5\">",
  "              <h2 className=\"font-semibold text-green-900\">Import termine</h2>",
  "              <p className=\"mt-1 text-sm text-green-800\">",
  "                {result.created} eleves crees · {result.skipped} ignores · {result.errors?.length || 0} erreurs",
  "              </p>",
  "              {result.errors?.length > 0 && (",
  "                <details className=\"mt-2 text-xs\">",
  "                  <summary className=\"cursor-pointer\">Voir les erreurs</summary>",
  "                  <ul className=\"mt-2 list-disc pl-5\">",
  "                    {result.errors.slice(0, 30).map((e: any, i: number) => (",
  "                      <li key={i}>Ligne {e.row}: {e.reason}</li>",
  "                    ))}",
  "                  </ul>",
  "                </details>",
  "              )}",
  "            </div>",
  "          )}",
  "        </div>",
  "      )}",
  "",
  "      {tab === 'parents' && (",
  "        <div className=\"mt-6 space-y-4\">",
  "          <div className=\"rounded-lg border bg-white p-5\">",
  "            <h2 className=\"font-semibold\">Generer les comptes parents</h2>",
  "            <p className=\"mt-1 text-sm text-gray-500\">",
  "              Cree un compte de connexion pour chaque parent (tuteur) qui n'en a pas encore, afin qu'il puisse acceder au portail parent et voir les notes, factures et presences de ses enfants.",
  "            </p>",
  "            <button onClick={generateParents} disabled={busy}",
  "                    className=\"mt-3 rounded bg-brand-600 px-4 py-2 text-sm text-white hover:bg-brand-700 disabled:opacity-50\">",
  "              {busy ? '…' : 'Generer les comptes parents'}",
  "            </button>",
  "          </div>",
  "",
  "          {parentResult && (",
  "            <div className=\"rounded-lg border bg-white p-5\">",
  "              <div className=\"flex items-center justify-between\">",
  "                <h2 className=\"font-semibold\">Resultat</h2>",
  "                {parentResult.generated.length > 0 && (",
  "                  <button onClick={downloadCsv} className=\"rounded border px-3 py-1 text-xs hover:bg-gray-50\">",
  "                    Telecharger CSV",
  "                  </button>",
  "                )}",
  "              </div>",
  "              <p className=\"mt-2 text-sm\">",
  "                <strong>{parentResult.generated.length}</strong> comptes crees · ",
  "                {parentResult.skipped.length} ignores · ",
  "                {parentResult.totalGuardiansWithoutAccount} parents sans compte initialement",
  "              </p>",
  "              {parentResult.generated.length > 0 && (",
  "                <>",
  "                  <p className=\"mt-2 rounded border border-yellow-200 bg-yellow-50 p-2 text-xs text-yellow-800\">",
  "                    IMPORTANT : Notez ou telechargez ces mots de passe maintenant. Ils ne seront plus visibles apres.",
  "                  </p>",
  "                  <div className=\"mt-3 max-h-96 overflow-y-auto\">",
  "                    <table className=\"w-full border-collapse text-xs\">",
  "                      <thead className=\"bg-gray-50 text-left\">",
  "                        <tr>",
  "                          <th className=\"p-2\">Parent</th>",
  "                          <th className=\"p-2\">Email de connexion</th>",
  "                          <th className=\"p-2\">Mot de passe</th>",
  "                          <th className=\"p-2 text-center\">Enfants</th>",
  "                        </tr>",
  "                      </thead>",
  "                      <tbody>",
  "                        {parentResult.generated.map((g: any, i: number) => (",
  "                          <tr key={i} className=\"border-t\">",
  "                            <td className=\"p-2\">{g.guardian}</td>",
  "                            <td className=\"p-2 font-mono\">{g.email}</td>",
  "                            <td className=\"p-2 font-mono font-bold\">{g.password}</td>",
  "                            <td className=\"p-2 text-center\">{g.childCount}</td>",
  "                          </tr>",
  "                        ))}",
  "                      </tbody>",
  "                    </table>",
  "                  </div>",
  "                </>",
  "              )}",
  "              {parentResult.skipped.length > 0 && (",
  "                <details className=\"mt-3 text-xs\">",
  "                  <summary className=\"cursor-pointer text-gray-600\">Ignores ({parentResult.skipped.length})</summary>",
  "                  <ul className=\"mt-2 list-disc pl-5\">",
  "                    {parentResult.skipped.map((s: any, i: number) => (",
  "                      <li key={i}>{s.guardian}: {s.reason}</li>",
  "                    ))}",
  "                  </ul>",
  "                </details>",
  "              )}",
  "            </div>",
  "          )}",
  "        </div>",
  "      )}",
  "    </div>",
  "  );",
  "}",
  ""
]));

// ============ SIDEBAR UPDATE ============
put('apps/web/app/[locale]/dashboard/layout.tsx', L([
  "import Link from 'next/link';",
  "import LanguageSwitcher from '@/components/LanguageSwitcher';",
  "import UserMenu from '@/components/UserMenu';",
  "import NotificationBell from '@/components/NotificationBell';",
  "",
  "type NavKey =",
  "  | 'dashboard' | 'students' | 'parents' | 'staff' | 'classes'",
  "  | 'subjects' | 'attendance' | 'exams' | 'finance' | 'timetable'",
  "  | 'library' | 'payroll' | 'import' | 'announcements' | 'settings';",
  "",
  "const NAV: NavKey[] = [",
  "  'dashboard',",
  "  'students',",
  "  'parents',",
  "  'staff',",
  "  'classes',",
  "  'subjects',",
  "  'timetable',",
  "  'attendance',",
  "  'exams',",
  "  'finance',",
  "  'library',",
  "  'payroll',",
  "  'import',",
  "  'announcements',",
  "  'settings',",
  "];",
  "",
  "const LABELS: Record<NavKey, { en: string; fr: string; ar: string }> = {",
  "  dashboard:     { en: 'Dashboard',     fr: 'Tableau de bord', ar: 'لوحة التحكم' },",
  "  students:      { en: 'Students',      fr: 'Eleves',          ar: 'الطلاب' },",
  "  parents:       { en: 'Parents',       fr: 'Parents',         ar: 'أولياء الأمور' },",
  "  staff:         { en: 'Staff',         fr: 'Personnel',       ar: 'الموظفون' },",
  "  classes:       { en: 'Classes',       fr: 'Classes',         ar: 'الفصول' },",
  "  subjects:      { en: 'Subjects',      fr: 'Matieres',        ar: 'المواد' },",
  "  timetable:     { en: 'Timetable',     fr: 'Emploi du temps', ar: 'الجدول' },",
  "  attendance:    { en: 'Attendance',    fr: 'Presence',        ar: 'الحضور' },",
  "  exams:         { en: 'Exams',         fr: 'Examens',         ar: 'الامتحانات' },",
  "  finance:       { en: 'Finance',       fr: 'Finances',        ar: 'المالية' },",
  "  library:       { en: 'Library',       fr: 'Bibliotheque',    ar: 'المكتبة' },",
  "  payroll:       { en: 'Payroll',       fr: 'Paie',            ar: 'الرواتب' },",
  "  import:        { en: 'Bulk Import',   fr: 'Import en masse', ar: 'الاستيراد' },",
  "  announcements: { en: 'Announcements', fr: 'Annonces',        ar: 'الإعلانات' },",
  "  settings:      { en: 'Settings',      fr: 'Parametres',      ar: 'الإعدادات' },",
  "};",
  "",
  "const ICONS: Record<NavKey, string> = {",
  "  dashboard: '📊', students: '🎓', parents: '👨‍👩‍👧', staff: '👩‍🏫',",
  "  classes: '🏫', subjects: '📚', timetable: '📅', attendance: '✅',",
  "  exams: '📝', finance: '💰', library: '📖', payroll: '💵',",
  "  import: '📥', announcements: '📢', settings: '⚙️',",
  "};",
  "",
  "export default function DashboardLayout({",
  "  children, params: { locale },",
  "}: { children: React.ReactNode; params: { locale: string } }) {",
  "  const l = locale === 'en' || locale === 'ar' ? locale : 'fr';",
  "",
  "  return (",
  "    <div className=\"flex min-h-screen bg-gray-50\">",
  "      <aside className=\"w-64 overflow-y-auto border-r bg-white\">",
  "        <div className=\"flex h-16 items-center border-b px-4\">",
  "          <span className=\"text-lg font-bold text-brand-600\">SMS</span>",
  "          <span className=\"ml-2 text-xs text-gray-400\">LBY</span>",
  "        </div>",
  "        <nav className=\"p-3 space-y-1\">",
  "          {NAV.map((k) => (",
  "            <Link",
  "              key={k}",
  "              href={'/' + locale + '/dashboard' + (k === 'dashboard' ? '' : '/' + k)}",
  "              className=\"flex items-center gap-3 rounded-lg px-3 py-2 text-sm text-gray-700 hover:bg-gray-100\"",
  "            >",
  "              <span className=\"text-base\">{ICONS[k]}</span>",
  "              <span>{LABELS[k][l]}</span>",
  "            </Link>",
  "          ))}",
  "        </nav>",
  "      </aside>",
  "      <div className=\"flex-1\">",
  "        <header className=\"flex h-16 items-center justify-between border-b bg-white px-6\">",
  "          <div />",
  "          <div className=\"flex items-center gap-3\">",
  "            <NotificationBell />",
  "            <LanguageSwitcher />",
  "            <UserMenu />",
  "          </div>",
  "        </header>",
  "        <main className=\"p-8\">{children}</main>",
  "      </div>",
  "    </div>",
  "  );",
  "}",
  ""
]));

console.log('\n✅ Payroll, Import, and sidebar written');