import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const root = process.cwd();
const put = (p, c) => {
  const full = join(root, p);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, c, 'utf8');
  console.log('  + ' + p);
};
const L = (a) => a.join('\n');

// ============ TIMETABLE PAGE ============
put('apps/web/app/[locale]/dashboard/timetable/page.tsx', L([
  "'use client';",
  "import { useEffect, useState } from 'react';",
  "import { useParams } from 'next/navigation';",
  "import { apiFetch } from '@/lib/api';",
  "",
  "const DAYS = ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'];",
  "const DAYS_EN = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];",
  "const DAYS_AR = ['الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت'];",
  "",
  "type Slot = {",
  "  id: string;",
  "  dayOfWeek: number;",
  "  startTime: string;",
  "  endTime: string;",
  "  room: string | null;",
  "  subject: { id: string; name: string; code: string };",
  "  teacher: { id: string; firstName: string; lastName: string } | null;",
  "};",
  "",
  "export default function TimetablePage() {",
  "  const { locale } = useParams() as { locale: string };",
  "  const l = locale === 'en' || locale === 'ar' ? locale : 'fr';",
  "  const [classes, setClasses] = useState<any[]>([]);",
  "  const [subjects, setSubjects] = useState<any[]>([]);",
  "  const [staff, setStaff] = useState<any[]>([]);",
  "  const [classId, setClassId] = useState('');",
  "  const [slots, setSlots] = useState<Slot[]>([]);",
  "  const [showNew, setShowNew] = useState(false);",
  "  const [editSlot, setEditSlot] = useState<Slot | null>(null);",
  "  const [err, setErr] = useState<string | null>(null);",
  "",
  "  const T = {",
  "    title:   { en: 'Timetable', fr: 'Emploi du temps', ar: 'الجدول' },",
  "    newSlot: { en: 'Add slot', fr: 'Ajouter un cours', ar: 'إضافة حصة' },",
  "    empty:   { en: 'No courses scheduled.', fr: 'Aucun cours programme.', ar: 'لا توجد حصص.' },",
  "    room:    { en: 'Room', fr: 'Salle', ar: 'القاعة' },",
  "  };",
  "",
  "  useEffect(() => {",
  "    Promise.all([",
  "      apiFetch('/api/v1/classes').then((r) => r.ok ? r.json() : []),",
  "      apiFetch('/api/v1/subjects').then((r) => r.ok ? r.json() : []),",
  "      apiFetch('/api/v1/staff').then((r) => r.ok ? r.json() : []),",
  "    ]).then(([c, s, st]) => {",
  "      setClasses(Array.isArray(c) ? c : []);",
  "      setSubjects(Array.isArray(s) ? s : []);",
  "      setStaff(Array.isArray(st) ? st : []);",
  "      if (c[0]?.id) setClassId(c[0].id);",
  "    }).catch((e) => setErr(String(e)));",
  "  }, []);",
  "",
  "  const load = () => {",
  "    if (!classId) return;",
  "    apiFetch('/api/v1/timetable/class/' + classId)",
  "      .then((r) => r.ok ? r.json() : [])",
  "      .then((d) => setSlots(Array.isArray(d) ? d : []))",
  "      .catch((e) => setErr(String(e)));",
  "  };",
  "  useEffect(load, [classId]);",
  "",
  "  const remove = async (id: string) => {",
  "    if (!confirm('Supprimer ce cours ?')) return;",
  "    await apiFetch('/api/v1/timetable/' + id, { method: 'DELETE' });",
  "    load();",
  "  };",
  "",
  "  const days = l === 'en' ? DAYS_EN : l === 'ar' ? DAYS_AR : DAYS;",
  "",
  "  return (",
  "    <div>",
  "      <div className=\"flex flex-wrap items-center justify-between gap-3\">",
  "        <h1 className=\"text-2xl font-bold\">{T.title[l]}</h1>",
  "        <div className=\"flex items-center gap-2\">",
  "          <select value={classId} onChange={(e) => setClassId(e.target.value)}",
  "                  className=\"rounded border px-3 py-2 text-sm\">",
  "            {classes.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}",
  "          </select>",
  "          <button onClick={() => setShowNew(true)} disabled={!classId}",
  "                  className=\"rounded-lg bg-brand-600 px-4 py-2 text-sm text-white hover:bg-brand-700 disabled:opacity-50\">",
  "            + {T.newSlot[l]}",
  "          </button>",
  "        </div>",
  "      </div>",
  "",
  "      {err && <p className=\"mt-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800\">{err}</p>}",
  "",
  "      <div className=\"mt-6 overflow-x-auto rounded-lg border bg-white\">",
  "        <table className=\"w-full border-collapse text-sm\">",
  "          <thead className=\"bg-gray-50\">",
  "            <tr>",
  "              {days.map((d) => (",
  "                <th key={d} className=\"border-r p-3 text-left font-medium last:border-r-0\">{d}</th>",
  "              ))}",
  "            </tr>",
  "          </thead>",
  "          <tbody>",
  "            <tr>",
  "              {[1, 2, 3, 4, 5, 6].map((day) => {",
  "                const daySlots = slots.filter((s) => s.dayOfWeek === day);",
  "                return (",
  "                  <td key={day} className=\"border-r border-t p-2 align-top last:border-r-0\">",
  "                    {daySlots.length === 0 && (",
  "                      <div className=\"text-xs text-gray-300\">—</div>",
  "                    )}",
  "                    {daySlots.map((s) => (",
  "                      <div key={s.id} className=\"mb-2 rounded border border-teal-200 bg-teal-50 p-2 text-xs\">",
  "                        <div className=\"flex items-start justify-between gap-1\">",
  "                          <div className=\"min-w-0 flex-1\">",
  "                            <div className=\"font-semibold text-teal-900\">{s.subject.code}</div>",
  "                            <div className=\"text-[10px] text-teal-700\">{s.startTime}–{s.endTime}</div>",
  "                            {s.teacher && (",
  "                              <div className=\"mt-1 text-[10px] text-gray-600\">",
  "                                {s.teacher.firstName} {s.teacher.lastName}",
  "                              </div>",
  "                            )}",
  "                            {s.room && <div className=\"text-[10px] text-gray-500\">{T.room[l]}: {s.room}</div>}",
  "                          </div>",
  "                          <div className=\"flex flex-col gap-1\">",
  "                            <button onClick={() => setEditSlot(s)} className=\"text-[10px] text-gray-500 hover:text-brand-700\">✏️</button>",
  "                            <button onClick={() => remove(s.id)} className=\"text-[10px] text-gray-500 hover:text-red-600\">✕</button>",
  "                          </div>",
  "                        </div>",
  "                      </div>",
  "                    ))}",
  "                  </td>",
  "                );",
  "              })}",
  "            </tr>",
  "          </tbody>",
  "        </table>",
  "      </div>",
  "",
  "      {(showNew || editSlot) && (",
  "        <SlotModal",
  "          classId={classId}",
  "          slot={editSlot}",
  "          subjects={subjects}",
  "          staff={staff}",
  "          onClose={() => { setShowNew(false); setEditSlot(null); }}",
  "          onSaved={() => { setShowNew(false); setEditSlot(null); load(); }}",
  "        />",
  "      )}",
  "    </div>",
  "  );",
  "}",
  "",
  "function SlotModal({ classId, slot, subjects, staff, onClose, onSaved }: any) {",
  "  const isEdit = !!slot;",
  "  const [form, setForm] = useState({",
  "    subjectId: slot?.subject?.id ?? subjects[0]?.id ?? '',",
  "    teacherId: slot?.teacher?.id ?? '',",
  "    dayOfWeek: slot?.dayOfWeek ?? 1,",
  "    startTime: slot?.startTime ?? '08:00',",
  "    endTime: slot?.endTime ?? '09:00',",
  "    room: slot?.room ?? '',",
  "  });",
  "  const [saving, setSaving] = useState(false);",
  "  const [err, setErr] = useState<string | null>(null);",
  "",
  "  const submit = async (e: React.FormEvent) => {",
  "    e.preventDefault();",
  "    setSaving(true); setErr(null);",
  "    try {",
  "      const url = isEdit ? '/api/v1/timetable/' + slot.id : '/api/v1/timetable';",
  "      const method = isEdit ? 'PUT' : 'POST';",
  "      const body: any = { ...form };",
  "      if (!isEdit) body.classId = classId;",
  "      const r = await apiFetch(url, { method, body: JSON.stringify(body) });",
  "      if (!r.ok) {",
  "        const txt = await r.text();",
  "        if (txt.includes('class_time_conflict')) { setErr('Conflit horaire pour cette classe.'); setSaving(false); return; }",
  "        if (txt.includes('teacher_time_conflict')) { setErr('Ce professeur a deja un cours sur ce creneau.'); setSaving(false); return; }",
  "        if (txt.includes('invalid_time_range')) { setErr('L\\'heure de fin doit etre apres le debut.'); setSaving(false); return; }",
  "        throw new Error(txt);",
  "      }",
  "      onSaved();",
  "    } catch (e: any) { setErr(String(e)); setSaving(false); }",
  "  };",
  "",
  "  return (",
  "    <div className=\"fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4\" onClick={onClose}>",
  "      <form onSubmit={submit} onClick={(e) => e.stopPropagation()}",
  "            className=\"w-full max-w-md space-y-4 rounded-xl bg-white p-6 shadow-xl\">",
  "        <h3 className=\"text-lg font-semibold\">{isEdit ? 'Modifier le cours' : 'Ajouter un cours'}</h3>",
  "        <label className=\"block\">",
  "          <span className=\"mb-1 block text-xs font-medium\">Matiere</span>",
  "          <select required value={form.subjectId} onChange={(e) => setForm({ ...form, subjectId: e.target.value })}",
  "                  className=\"w-full rounded border px-3 py-2\">",
  "            {subjects.map((s) => <option key={s.id} value={s.id}>{s.code} — {s.name}</option>)}",
  "          </select>",
  "        </label>",
  "        <label className=\"block\">",
  "          <span className=\"mb-1 block text-xs font-medium\">Enseignant</span>",
  "          <select value={form.teacherId} onChange={(e) => setForm({ ...form, teacherId: e.target.value })}",
  "                  className=\"w-full rounded border px-3 py-2\">",
  "            <option value=\"\">—</option>",
  "            {staff.map((s) => <option key={s.id} value={s.id}>{s.firstName} {s.lastName} ({s.position})</option>)}",
  "          </select>",
  "        </label>",
  "        <label className=\"block\">",
  "          <span className=\"mb-1 block text-xs font-medium\">Jour</span>",
  "          <select value={form.dayOfWeek} onChange={(e) => setForm({ ...form, dayOfWeek: Number(e.target.value) })}",
  "                  className=\"w-full rounded border px-3 py-2\">",
  "            <option value={1}>Lundi</option>",
  "            <option value={2}>Mardi</option>",
  "            <option value={3}>Mercredi</option>",
  "            <option value={4}>Jeudi</option>",
  "            <option value={5}>Vendredi</option>",
  "            <option value={6}>Samedi</option>",
  "          </select>",
  "        </label>",
  "        <div className=\"grid grid-cols-2 gap-3\">",
  "          <label className=\"block\">",
  "            <span className=\"mb-1 block text-xs font-medium\">Debut</span>",
  "            <input type=\"time\" required value={form.startTime} onChange={(e) => setForm({ ...form, startTime: e.target.value })}",
  "                   className=\"w-full rounded border px-3 py-2\" />",
  "          </label>",
  "          <label className=\"block\">",
  "            <span className=\"mb-1 block text-xs font-medium\">Fin</span>",
  "            <input type=\"time\" required value={form.endTime} onChange={(e) => setForm({ ...form, endTime: e.target.value })}",
  "                   className=\"w-full rounded border px-3 py-2\" />",
  "          </label>",
  "        </div>",
  "        <label className=\"block\">",
  "          <span className=\"mb-1 block text-xs font-medium\">Salle</span>",
  "          <input value={form.room} onChange={(e) => setForm({ ...form, room: e.target.value })}",
  "                 placeholder=\"Salle 12\" className=\"w-full rounded border px-3 py-2\" />",
  "        </label>",
  "        {err && <p className=\"text-sm text-red-600\">{err}</p>}",
  "        <div className=\"flex justify-end gap-2 pt-2\">",
  "          <button type=\"button\" onClick={onClose} className=\"rounded border px-4 py-2 text-sm\">Annuler</button>",
  "          <button disabled={saving} className=\"rounded bg-brand-600 px-4 py-2 text-sm text-white hover:bg-brand-700 disabled:opacity-50\">",
  "            {saving ? '…' : 'Enregistrer'}",
  "          </button>",
  "        </div>",
  "      </form>",
  "    </div>",
  "  );",
  "}",
  ""
]));

// ============ LIBRARY PAGE ============
put('apps/web/app/[locale]/dashboard/library/page.tsx', L([
  "'use client';",
  "import { useEffect, useState } from 'react';",
  "import { useParams } from 'next/navigation';",
  "import { apiFetch } from '@/lib/api';",
  "",
  "export default function LibraryPage() {",
  "  const { locale } = useParams() as { locale: string };",
  "  const l = locale === 'en' || locale === 'ar' ? locale : 'fr';",
  "  const [tab, setTab] = useState<'books' | 'loans'>('books');",
  "  const [books, setBooks] = useState<any[]>([]);",
  "  const [loans, setLoans] = useState<any[]>([]);",
  "  const [students, setStudents] = useState<any[]>([]);",
  "  const [q, setQ] = useState('');",
  "  const [showBook, setShowBook] = useState(false);",
  "  const [editBook, setEditBook] = useState<any>(null);",
  "  const [showIssue, setShowIssue] = useState(false);",
  "  const [returnFor, setReturnFor] = useState<any>(null);",
  "  const [err, setErr] = useState<string | null>(null);",
  "  const [ok, setOk] = useState<string | null>(null);",
  "",
  "  const T = {",
  "    title:    { en: 'Library', fr: 'Bibliotheque', ar: 'المكتبة' },",
  "    books:    { en: 'Books', fr: 'Livres', ar: 'الكتب' },",
  "    loans:    { en: 'Loans', fr: 'Emprunts', ar: 'الإعارات' },",
  "    newBook:  { en: 'New book', fr: 'Nouveau livre', ar: 'كتاب جديد' },",
  "    issue:    { en: 'Issue loan', fr: 'Preter un livre', ar: 'إعارة' },",
  "    search:   { en: 'Search…', fr: 'Rechercher…', ar: 'بحث…' },",
  "    empty:    { en: 'Nothing here.', fr: 'Rien ici.', ar: 'لا شيء.' },",
  "    title_:   { en: 'Title', fr: 'Titre', ar: 'العنوان' },",
  "    author:   { en: 'Author', fr: 'Auteur', ar: 'المؤلف' },",
  "    category: { en: 'Category', fr: 'Categorie', ar: 'التصنيف' },",
  "    stock:    { en: 'Available', fr: 'Disponible', ar: 'متوفر' },",
  "    book:     { en: 'Book', fr: 'Livre', ar: 'الكتاب' },",
  "    student:  { en: 'Student', fr: 'Eleve', ar: 'الطالب' },",
  "    borrowed: { en: 'Borrowed', fr: 'Emprunte le', ar: 'تاريخ الإعارة' },",
  "    due:      { en: 'Due', fr: 'Echeance', ar: 'الاستحقاق' },",
  "    status:   { en: 'Status', fr: 'Statut', ar: 'الحالة' },",
  "    overdue:  { en: 'Mark overdue', fr: 'Marquer en retard', ar: 'تحديد المتأخر' },",
  "    return:   { en: 'Return', fr: 'Retourner', ar: 'إرجاع' },",
  "  };",
  "",
  "  const loadBooks = () => {",
  "    const qs = q ? '?q=' + encodeURIComponent(q) : '';",
  "    apiFetch('/api/v1/library/books' + qs)",
  "      .then((r) => r.ok ? r.json() : []).then((d) => setBooks(Array.isArray(d) ? d : []));",
  "  };",
  "  const loadLoans = () => {",
  "    apiFetch('/api/v1/library/loans')",
  "      .then((r) => r.ok ? r.json() : []).then((d) => setLoans(Array.isArray(d) ? d : []));",
  "  };",
  "",
  "  useEffect(() => { loadBooks(); loadLoans(); }, []);",
  "  useEffect(() => {",
  "    apiFetch('/api/v1/students').then((r) => r.ok ? r.json() : []).then((d) => setStudents(Array.isArray(d) ? d : []));",
  "  }, []);",
  "",
  "  const markOverdue = async () => {",
  "    const r = await apiFetch('/api/v1/library/loans/mark-overdue', { method: 'POST' });",
  "    if (r.ok) { setOk('Retards mis a jour.'); loadLoans(); }",
  "  };",
  "",
  "  return (",
  "    <div>",
  "      <div className=\"flex items-center justify-between\">",
  "        <h1 className=\"text-2xl font-bold\">{T.title[l]}</h1>",
  "        <div className=\"flex gap-2\">",
  "          {tab === 'books' && (",
  "            <button onClick={() => setShowBook(true)} className=\"rounded-lg bg-brand-600 px-4 py-2 text-sm text-white hover:bg-brand-700\">",
  "              + {T.newBook[l]}",
  "            </button>",
  "          )}",
  "          {tab === 'loans' && (",
  "            <>",
  "              <button onClick={markOverdue} className=\"rounded border px-3 py-2 text-sm hover:bg-gray-50\">{T.overdue[l]}</button>",
  "              <button onClick={() => setShowIssue(true)} className=\"rounded-lg bg-brand-600 px-4 py-2 text-sm text-white hover:bg-brand-700\">",
  "                + {T.issue[l]}",
  "              </button>",
  "            </>",
  "          )}",
  "        </div>",
  "      </div>",
  "",
  "      <div className=\"mt-6 flex gap-2 border-b\">",
  "        {(['books','loans'] as const).map((x) => (",
  "          <button key={x} onClick={() => setTab(x)}",
  "                  className={'border-b-2 px-4 py-2 text-sm ' + (tab === x ? 'border-brand-600 font-medium text-brand-700' : 'border-transparent text-gray-600')}>",
  "            {T[x][l]}",
  "          </button>",
  "        ))}",
  "      </div>",
  "",
  "      {err && <p className=\"mt-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800\">{err}</p>}",
  "      {ok && <p className=\"mt-4 rounded border border-green-200 bg-green-50 p-3 text-sm text-green-800\">{ok}</p>}",
  "",
  "      {tab === 'books' && (",
  "        <>",
  "          <input value={q} onChange={(e) => setQ(e.target.value)}",
  "                 onKeyDown={(e) => e.key === 'Enter' && loadBooks()}",
  "                 placeholder={T.search[l]}",
  "                 className=\"mt-4 w-64 rounded border px-3 py-2 text-sm\" />",
  "          <div className=\"mt-4 overflow-x-auto rounded-lg border bg-white\">",
  "            <table className=\"w-full border-collapse text-sm\">",
  "              <thead className=\"bg-gray-50 text-left\">",
  "                <tr>",
  "                  <th className=\"p-3 font-medium\">{T.title_[l]}</th>",
  "                  <th className=\"p-3 font-medium\">{T.author[l]}</th>",
  "                  <th className=\"p-3 font-medium\">{T.category[l]}</th>",
  "                  <th className=\"p-3 text-center font-medium\">{T.stock[l]}</th>",
  "                  <th className=\"p-3\"></th>",
  "                </tr>",
  "              </thead>",
  "              <tbody>",
  "                {books.length === 0 && <tr><td colSpan={5} className=\"p-6 text-center text-gray-500\">{T.empty[l]}</td></tr>}",
  "                {books.map((b) => (",
  "                  <tr key={b.id} className=\"border-t hover:bg-gray-50\">",
  "                    <td className=\"p-3\"><div className=\"font-medium\">{b.title}</div>{b.isbn && <div className=\"text-[10px] text-gray-400\">{b.isbn}</div>}</td>",
  "                    <td className=\"p-3 text-xs\">{b.author || '—'}</td>",
  "                    <td className=\"p-3 text-xs\">{b.category || '—'}</td>",
  "                    <td className=\"p-3 text-center\">",
  "                      <span className={'rounded-full px-2 py-0.5 text-xs font-medium ' + (b.available > 0 ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800')}>",
  "                        {b.available}/{b.totalCopies}",
  "                      </span>",
  "                    </td>",
  "                    <td className=\"p-3 text-right whitespace-nowrap\">",
  "                      <button onClick={() => setEditBook(b)} className=\"rounded border border-gray-300 px-3 py-1 text-xs hover:bg-gray-50\">✏️</button>",
  "                      <button onClick={async () => {",
  "                        if (!confirm('Supprimer ce livre ?')) return;",
  "                        const r = await apiFetch('/api/v1/library/books/' + b.id, { method: 'DELETE' });",
  "                        if (!r.ok) { setErr((await r.text()).includes('book_has_active_loans') ? 'Emprunts actifs — impossible de supprimer.' : 'Erreur'); return; }",
  "                        loadBooks();",
  "                      }} className=\"ml-2 rounded border border-red-300 px-3 py-1 text-xs text-red-700 hover:bg-red-50\">Suppr.</button>",
  "                    </td>",
  "                  </tr>",
  "                ))}",
  "              </tbody>",
  "            </table>",
  "          </div>",
  "        </>",
  "      )}",
  "",
  "      {tab === 'loans' && (",
  "        <div className=\"mt-4 overflow-x-auto rounded-lg border bg-white\">",
  "          <table className=\"w-full border-collapse text-sm\">",
  "            <thead className=\"bg-gray-50 text-left\">",
  "              <tr>",
  "                <th className=\"p-3 font-medium\">{T.book[l]}</th>",
  "                <th className=\"p-3 font-medium\">{T.student[l]}</th>",
  "                <th className=\"p-3 font-medium\">{T.borrowed[l]}</th>",
  "                <th className=\"p-3 font-medium\">{T.due[l]}</th>",
  "                <th className=\"p-3 font-medium\">{T.status[l]}</th>",
  "                <th className=\"p-3\"></th>",
  "              </tr>",
  "            </thead>",
  "            <tbody>",
  "              {loans.length === 0 && <tr><td colSpan={6} className=\"p-6 text-center text-gray-500\">{T.empty[l]}</td></tr>}",
  "              {loans.map((ln) => (",
  "                <tr key={ln.id} className=\"border-t hover:bg-gray-50\">",
  "                  <td className=\"p-3\"><div className=\"font-medium\">{ln.book.title}</div><div className=\"text-[10px] text-gray-400\">{ln.book.author}</div></td>",
  "                  <td className=\"p-3 text-xs\">{ln.student.firstName} {ln.student.lastName}<div className=\"font-mono text-[10px] text-gray-400\">{ln.student.admissionNo}</div></td>",
  "                  <td className=\"p-3 text-xs\">{new Date(ln.borrowedAt).toLocaleDateString()}</td>",
  "                  <td className=\"p-3 text-xs\">{new Date(ln.dueDate).toLocaleDateString()}</td>",
  "                  <td className=\"p-3\">",
  "                    <span className={'rounded-full px-2 py-0.5 text-xs font-medium ' +",
  "                      (ln.status === 'RETURNED' ? 'bg-gray-100 text-gray-700' : ln.status === 'OVERDUE' ? 'bg-red-100 text-red-800' : 'bg-yellow-100 text-yellow-800')}>",
  "                      {ln.status}",
  "                    </span>",
  "                    {ln.fine > 0 && <div className=\"text-[10px] text-red-600\">{ln.fine} XAF</div>}",
  "                  </td>",
  "                  <td className=\"p-3 text-right\">",
  "                    {ln.status !== 'RETURNED' && (",
  "                      <button onClick={() => setReturnFor(ln)} className=\"rounded bg-brand-600 px-3 py-1 text-xs text-white hover:bg-brand-700\">{T.return[l]}</button>",
  "                    )}",
  "                  </td>",
  "                </tr>",
  "              ))}",
  "            </tbody>",
  "          </table>",
  "        </div>",
  "      )}",
  "",
  "      {(showBook || editBook) && (",
  "        <BookModal book={editBook} onClose={() => { setShowBook(false); setEditBook(null); }} onSaved={() => { setShowBook(false); setEditBook(null); loadBooks(); }} />",
  "      )}",
  "      {showIssue && (",
  "        <IssueModal books={books} students={students} onClose={() => setShowIssue(false)} onSaved={() => { setShowIssue(false); loadLoans(); loadBooks(); }} />",
  "      )}",
  "      {returnFor && (",
  "        <ReturnModal loan={returnFor} onClose={() => setReturnFor(null)} onSaved={() => { setReturnFor(null); loadLoans(); loadBooks(); }} />",
  "      )}",
  "    </div>",
  "  );",
  "}",
  "",
  "function BookModal({ book, onClose, onSaved }: any) {",
  "  const isEdit = !!book;",
  "  const [form, setForm] = useState({",
  "    title: book?.title ?? '',",
  "    author: book?.author ?? '',",
  "    isbn: book?.isbn ?? '',",
  "    publisher: book?.publisher ?? '',",
  "    category: book?.category ?? '',",
  "    shelf: book?.shelf ?? '',",
  "    totalCopies: book?.totalCopies ?? 1,",
  "  });",
  "  const [saving, setSaving] = useState(false);",
  "  const [err, setErr] = useState<string | null>(null);",
  "",
  "  const submit = async (e: React.FormEvent) => {",
  "    e.preventDefault(); setSaving(true); setErr(null);",
  "    try {",
  "      const url = isEdit ? '/api/v1/library/books/' + book.id : '/api/v1/library/books';",
  "      const method = isEdit ? 'PUT' : 'POST';",
  "      const r = await apiFetch(url, { method, body: JSON.stringify({ ...form, totalCopies: Number(form.totalCopies) }) });",
  "      if (!r.ok) throw new Error(await r.text());",
  "      onSaved();",
  "    } catch (e: any) { setErr(String(e)); setSaving(false); }",
  "  };",
  "",
  "  return (",
  "    <div className=\"fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4\" onClick={onClose}>",
  "      <form onSubmit={submit} onClick={(e) => e.stopPropagation()} className=\"w-full max-w-md space-y-3 rounded-xl bg-white p-6 shadow-xl\">",
  "        <h3 className=\"text-lg font-semibold\">{isEdit ? 'Modifier' : 'Nouveau livre'}</h3>",
  "        <input required placeholder=\"Titre\" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} className=\"w-full rounded border px-3 py-2\" />",
  "        <input placeholder=\"Auteur\" value={form.author} onChange={(e) => setForm({ ...form, author: e.target.value })} className=\"w-full rounded border px-3 py-2\" />",
  "        <input placeholder=\"ISBN\" value={form.isbn} onChange={(e) => setForm({ ...form, isbn: e.target.value })} className=\"w-full rounded border px-3 py-2\" />",
  "        <input placeholder=\"Editeur\" value={form.publisher} onChange={(e) => setForm({ ...form, publisher: e.target.value })} className=\"w-full rounded border px-3 py-2\" />",
  "        <input placeholder=\"Categorie\" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} className=\"w-full rounded border px-3 py-2\" />",
  "        <input placeholder=\"Rayon\" value={form.shelf} onChange={(e) => setForm({ ...form, shelf: e.target.value })} className=\"w-full rounded border px-3 py-2\" />",
  "        <input type=\"number\" min={1} placeholder=\"Exemplaires\" value={form.totalCopies} onChange={(e) => setForm({ ...form, totalCopies: Number(e.target.value) })} className=\"w-full rounded border px-3 py-2\" />",
  "        {err && <p className=\"text-sm text-red-600\">{err}</p>}",
  "        <div className=\"flex justify-end gap-2 pt-2\">",
  "          <button type=\"button\" onClick={onClose} className=\"rounded border px-4 py-2 text-sm\">Annuler</button>",
  "          <button disabled={saving} className=\"rounded bg-brand-600 px-4 py-2 text-sm text-white hover:bg-brand-700 disabled:opacity-50\">{saving ? '…' : 'Enregistrer'}</button>",
  "        </div>",
  "      </form>",
  "    </div>",
  "  );",
  "}",
  "",
  "function IssueModal({ books, students, onClose, onSaved }: any) {",
  "  const available = books.filter((b: any) => b.available > 0);",
  "  const [form, setForm] = useState({",
  "    bookId: available[0]?.id ?? '',",
  "    studentId: students[0]?.id ?? '',",
  "    dueDate: (() => { const d = new Date(); d.setDate(d.getDate() + 14); return d.toISOString().slice(0, 10); })(),",
  "  });",
  "  const [saving, setSaving] = useState(false);",
  "  const [err, setErr] = useState<string | null>(null);",
  "",
  "  const submit = async (e: React.FormEvent) => {",
  "    e.preventDefault(); setSaving(true); setErr(null);",
  "    try {",
  "      const r = await apiFetch('/api/v1/library/loans', { method: 'POST', body: JSON.stringify(form) });",
  "      if (!r.ok) throw new Error(await r.text());",
  "      onSaved();",
  "    } catch (e: any) { setErr(String(e)); setSaving(false); }",
  "  };",
  "",
  "  return (",
  "    <div className=\"fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4\" onClick={onClose}>",
  "      <form onSubmit={submit} onClick={(e) => e.stopPropagation()} className=\"w-full max-w-md space-y-3 rounded-xl bg-white p-6 shadow-xl\">",
  "        <h3 className=\"text-lg font-semibold\">Preter un livre</h3>",
  "        <label className=\"block\"><span className=\"text-xs\">Livre</span>",
  "          <select required value={form.bookId} onChange={(e) => setForm({ ...form, bookId: e.target.value })} className=\"mt-1 w-full rounded border px-3 py-2\">",
  "            {available.length === 0 && <option value=\"\">Aucun disponible</option>}",
  "            {available.map((b: any) => <option key={b.id} value={b.id}>{b.title} ({b.available})</option>)}",
  "          </select>",
  "        </label>",
  "        <label className=\"block\"><span className=\"text-xs\">Eleve</span>",
  "          <select required value={form.studentId} onChange={(e) => setForm({ ...form, studentId: e.target.value })} className=\"mt-1 w-full rounded border px-3 py-2\">",
  "            {students.map((s: any) => <option key={s.id} value={s.id}>{s.admissionNo} — {s.firstName} {s.lastName}</option>)}",
  "          </select>",
  "        </label>",
  "        <label className=\"block\"><span className=\"text-xs\">Echeance</span>",
  "          <input type=\"date\" value={form.dueDate} onChange={(e) => setForm({ ...form, dueDate: e.target.value })} className=\"mt-1 w-full rounded border px-3 py-2\" />",
  "        </label>",
  "        {err && <p className=\"text-sm text-red-600\">{err}</p>}",
  "        <div className=\"flex justify-end gap-2 pt-2\">",
  "          <button type=\"button\" onClick={onClose} className=\"rounded border px-4 py-2 text-sm\">Annuler</button>",
  "          <button disabled={saving} className=\"rounded bg-brand-600 px-4 py-2 text-sm text-white hover:bg-brand-700 disabled:opacity-50\">{saving ? '…' : 'Preter'}</button>",
  "        </div>",
  "      </form>",
  "    </div>",
  "  );",
  "}",
  "",
  "function ReturnModal({ loan, onClose, onSaved }: any) {",
  "  const [fine, setFine] = useState(loan.fine || 0);",
  "  const [saving, setSaving] = useState(false);",
  "  const submit = async (e: React.FormEvent) => {",
  "    e.preventDefault(); setSaving(true);",
  "    await apiFetch('/api/v1/library/loans/' + loan.id + '/return', { method: 'POST', body: JSON.stringify({ fine: Number(fine) }) });",
  "    onSaved();",
  "  };",
  "  return (",
  "    <div className=\"fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4\" onClick={onClose}>",
  "      <form onSubmit={submit} onClick={(e) => e.stopPropagation()} className=\"w-full max-w-sm space-y-3 rounded-xl bg-white p-6 shadow-xl\">",
  "        <h3 className=\"text-lg font-semibold\">Retourner le livre</h3>",
  "        <p className=\"text-sm text-gray-600\">{loan.book.title} — {loan.student.firstName} {loan.student.lastName}</p>",
  "        <label className=\"block\"><span className=\"text-xs\">Amende (XAF)</span>",
  "          <input type=\"number\" min={0} value={fine} onChange={(e) => setFine(Number(e.target.value))} className=\"mt-1 w-full rounded border px-3 py-2\" />",
  "        </label>",
  "        <div className=\"flex justify-end gap-2 pt-2\">",
  "          <button type=\"button\" onClick={onClose} className=\"rounded border px-4 py-2 text-sm\">Annuler</button>",
  "          <button disabled={saving} className=\"rounded bg-brand-600 px-4 py-2 text-sm text-white hover:bg-brand-700 disabled:opacity-50\">{saving ? '…' : 'Confirmer'}</button>",
  "        </div>",
  "      </form>",
  "    </div>",
  "  );",
  "}",
  ""
]));

console.log('\n✅ Timetable + Library pages written');