import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const root = process.cwd();
const put = (p, c) => {
  const full = join(root, p);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, c, 'utf8');
  console.log('  + ' + p);
};
const L = (a) => a.join('\n');

// ============ TIMETABLE ============
put('apps/api/src/timetable/timetable.service.ts', L([
  "import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';",
  "import { PrismaService } from '../prisma/prisma.service';",
  "",
  "@Injectable()",
  "export class TimetableService {",
  "  constructor(private prisma: PrismaService) {}",
  "",
  "  listByClass(classId: string) {",
  "    return this.prisma.timetableSlot.findMany({",
  "      where: { classId },",
  "      include: {",
  "        subject: { select: { id: true, name: true, code: true } },",
  "        teacher: { select: { id: true, firstName: true, lastName: true } },",
  "      },",
  "      orderBy: [{ dayOfWeek: 'asc' }, { startTime: 'asc' }],",
  "    });",
  "  }",
  "",
  "  listByTeacher(teacherId: string) {",
  "    return this.prisma.timetableSlot.findMany({",
  "      where: { teacherId },",
  "      include: {",
  "        subject: { select: { id: true, name: true, code: true } },",
  "        class: { select: { id: true, name: true } },",
  "      },",
  "      orderBy: [{ dayOfWeek: 'asc' }, { startTime: 'asc' }],",
  "    });",
  "  }",
  "",
  "  async create(schoolId: string, dto: any) {",
  "    if (!dto.classId || !dto.subjectId) throw new BadRequestException('class_and_subject_required');",
  "    if (dto.dayOfWeek === undefined || !dto.startTime || !dto.endTime) throw new BadRequestException('time_required');",
  "    if (dto.startTime >= dto.endTime) throw new BadRequestException('invalid_time_range');",
  "    const day = Number(dto.dayOfWeek);",
  "    const conflicts = await this.prisma.timetableSlot.findMany({ where: { classId: dto.classId, dayOfWeek: day } });",
  "    for (const c of conflicts) {",
  "      if (dto.startTime < c.endTime && dto.endTime > c.startTime) throw new BadRequestException('class_time_conflict');",
  "    }",
  "    if (dto.teacherId) {",
  "      const tc = await this.prisma.timetableSlot.findMany({ where: { teacherId: dto.teacherId, dayOfWeek: day } });",
  "      for (const c of tc) {",
  "        if (dto.startTime < c.endTime && dto.endTime > c.startTime) throw new BadRequestException('teacher_time_conflict');",
  "      }",
  "    }",
  "    return this.prisma.timetableSlot.create({",
  "      data: {",
  "        schoolId,",
  "        classId: dto.classId,",
  "        subjectId: dto.subjectId,",
  "        teacherId: dto.teacherId || null,",
  "        dayOfWeek: day,",
  "        startTime: dto.startTime,",
  "        endTime: dto.endTime,",
  "        room: dto.room || null,",
  "      },",
  "    });",
  "  }",
  "",
  "  async update(id: string, dto: any) {",
  "    const exists = await this.prisma.timetableSlot.findUnique({ where: { id } });",
  "    if (!exists) throw new NotFoundException('slot_not_found');",
  "    const data: any = {};",
  "    if (dto.subjectId !== undefined) data.subjectId = dto.subjectId;",
  "    if (dto.teacherId !== undefined) data.teacherId = dto.teacherId || null;",
  "    if (dto.dayOfWeek !== undefined) data.dayOfWeek = Number(dto.dayOfWeek);",
  "    if (dto.startTime !== undefined) data.startTime = dto.startTime;",
  "    if (dto.endTime !== undefined) data.endTime = dto.endTime;",
  "    if (dto.room !== undefined) data.room = dto.room || null;",
  "    return this.prisma.timetableSlot.update({ where: { id }, data });",
  "  }",
  "",
  "  async remove(id: string) {",
  "    await this.prisma.timetableSlot.delete({ where: { id } });",
  "    return { ok: true };",
  "  }",
  "}",
  ""
]));

put('apps/api/src/timetable/timetable.controller.ts', L([
  "import { Body, Controller, Delete, Get, Param, Post, Put, Req, UseGuards } from '@nestjs/common';",
  "import { TimetableService } from './timetable.service';",
  "import { JwtAuthGuard } from '../common/guards/jwt-auth.guard';",
  "",
  "@UseGuards(JwtAuthGuard)",
  "@Controller('timetable')",
  "export class TimetableController {",
  "  constructor(private svc: TimetableService) {}",
  "",
  "  @Get('class/:classId')",
  "  byClass(@Param('classId') classId: string) { return this.svc.listByClass(classId); }",
  "",
  "  @Get('teacher/:teacherId')",
  "  byTeacher(@Param('teacherId') teacherId: string) { return this.svc.listByTeacher(teacherId); }",
  "",
  "  @Post()",
  "  create(@Req() req: any, @Body() dto: any) { return this.svc.create(req.user.schoolId, dto); }",
  "",
  "  @Put(':id')",
  "  update(@Param('id') id: string, @Body() dto: any) { return this.svc.update(id, dto); }",
  "",
  "  @Delete(':id')",
  "  remove(@Param('id') id: string) { return this.svc.remove(id); }",
  "}",
  ""
]));

put('apps/api/src/timetable/timetable.module.ts', L([
  "import { Module } from '@nestjs/common';",
  "import { TimetableService } from './timetable.service';",
  "import { TimetableController } from './timetable.controller';",
  "",
  "@Module({ providers: [TimetableService], controllers: [TimetableController] })",
  "export class TimetableModule {}",
  ""
]));

// ============ LIBRARY ============
put('apps/api/src/library/library.service.ts', L([
  "import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';",
  "import { PrismaService } from '../prisma/prisma.service';",
  "",
  "@Injectable()",
  "export class LibraryService {",
  "  constructor(private prisma: PrismaService) {}",
  "",
  "  listBooks(schoolId: string, q?: string) {",
  "    const where: any = { schoolId };",
  "    if (q) {",
  "      where.OR = [",
  "        { title: { contains: q, mode: 'insensitive' } },",
  "        { author: { contains: q, mode: 'insensitive' } },",
  "        { isbn: { contains: q } },",
  "        { category: { contains: q, mode: 'insensitive' } },",
  "      ];",
  "    }",
  "    return this.prisma.book.findMany({ where, orderBy: { title: 'asc' }, take: 500 });",
  "  }",
  "",
  "  async createBook(schoolId: string, dto: any) {",
  "    const total = Number(dto.totalCopies) || 1;",
  "    return this.prisma.book.create({",
  "      data: {",
  "        schoolId,",
  "        isbn: dto.isbn || null,",
  "        title: dto.title,",
  "        author: dto.author || null,",
  "        publisher: dto.publisher || null,",
  "        category: dto.category || null,",
  "        shelf: dto.shelf || null,",
  "        totalCopies: total,",
  "        available: total,",
  "      },",
  "    });",
  "  }",
  "",
  "  async updateBook(id: string, dto: any) {",
  "    const b = await this.prisma.book.findUnique({ where: { id } });",
  "    if (!b) throw new NotFoundException('book_not_found');",
  "    const data: any = {};",
  "    for (const k of ['isbn', 'title', 'author', 'publisher', 'category', 'shelf']) {",
  "      if (dto[k] !== undefined) data[k] = dto[k] || null;",
  "    }",
  "    if (dto.totalCopies !== undefined) {",
  "      const borrowed = b.totalCopies - b.available;",
  "      const newTotal = Number(dto.totalCopies);",
  "      if (newTotal < borrowed) throw new BadRequestException('fewer_than_borrowed');",
  "      data.totalCopies = newTotal;",
  "      data.available = newTotal - borrowed;",
  "    }",
  "    return this.prisma.book.update({ where: { id }, data });",
  "  }",
  "",
  "  async removeBook(id: string) {",
  "    const active = await this.prisma.bookLoan.count({ where: { bookId: id, status: 'BORROWED' } });",
  "    if (active > 0) throw new BadRequestException('book_has_active_loans');",
  "    await this.prisma.book.delete({ where: { id } });",
  "    return { ok: true };",
  "  }",
  "",
  "  listLoans(schoolId: string, status?: string) {",
  "    const where: any = { schoolId };",
  "    if (status) where.status = status;",
  "    return this.prisma.bookLoan.findMany({",
  "      where,",
  "      include: {",
  "        book: { select: { id: true, title: true, author: true } },",
  "        student: { select: { id: true, firstName: true, lastName: true, admissionNo: true } },",
  "      },",
  "      orderBy: { borrowedAt: 'desc' },",
  "      take: 500,",
  "    });",
  "  }",
  "",
  "  async issue(schoolId: string, dto: any) {",
  "    const book = await this.prisma.book.findUnique({ where: { id: dto.bookId } });",
  "    if (!book) throw new NotFoundException('book_not_found');",
  "    if (book.available <= 0) throw new BadRequestException('no_copies_available');",
  "    const due = dto.dueDate ? new Date(dto.dueDate) : (() => { const d = new Date(); d.setDate(d.getDate() + 14); return d; })();",
  "    const loan = await this.prisma.bookLoan.create({",
  "      data: { schoolId, bookId: dto.bookId, studentId: dto.studentId, dueDate: due, status: 'BORROWED', notes: dto.notes || null },",
  "    });",
  "    await this.prisma.book.update({ where: { id: book.id }, data: { available: book.available - 1 } });",
  "    return loan;",
  "  }",
  "",
  "  async returnLoan(id: string, fine = 0) {",
  "    const loan = await this.prisma.bookLoan.findUnique({ where: { id } });",
  "    if (!loan) throw new NotFoundException('loan_not_found');",
  "    if (loan.status === 'RETURNED') throw new BadRequestException('already_returned');",
  "    await this.prisma.$transaction([",
  "      this.prisma.bookLoan.update({",
  "        where: { id },",
  "        data: { status: 'RETURNED', returnedAt: new Date(), fine: Number(fine) || 0 },",
  "      }),",
  "      this.prisma.book.update({ where: { id: loan.bookId }, data: { available: { increment: 1 } } }),",
  "    ]);",
  "    return { ok: true };",
  "  }",
  "",
  "  async markOverdue(schoolId: string) {",
  "    const now = new Date();",
  "    const overdue = await this.prisma.bookLoan.findMany({",
  "      where: { schoolId, status: 'BORROWED', dueDate: { lt: now } },",
  "    });",
  "    for (const l of overdue) {",
  "      const daysLate = Math.floor((now.getTime() - l.dueDate.getTime()) / 86400000);",
  "      const fine = daysLate * 100;",
  "      await this.prisma.bookLoan.update({ where: { id: l.id }, data: { status: 'OVERDUE', fine } });",
  "    }",
  "    return { updated: overdue.length };",
  "  }",
  "}",
  ""
]));

put('apps/api/src/library/library.controller.ts', L([
  "import { Body, Controller, Delete, Get, Param, Post, Put, Query, Req, UseGuards } from '@nestjs/common';",
  "import { LibraryService } from './library.service';",
  "import { JwtAuthGuard } from '../common/guards/jwt-auth.guard';",
  "",
  "@UseGuards(JwtAuthGuard)",
  "@Controller('library')",
  "export class LibraryController {",
  "  constructor(private svc: LibraryService) {}",
  "",
  "  @Get('books')",
  "  listBooks(@Req() req: any, @Query('q') q?: string) { return this.svc.listBooks(req.user.schoolId, q); }",
  "",
  "  @Post('books')",
  "  createBook(@Req() req: any, @Body() dto: any) { return this.svc.createBook(req.user.schoolId, dto); }",
  "",
  "  @Put('books/:id')",
  "  updateBook(@Param('id') id: string, @Body() dto: any) { return this.svc.updateBook(id, dto); }",
  "",
  "  @Delete('books/:id')",
  "  removeBook(@Param('id') id: string) { return this.svc.removeBook(id); }",
  "",
  "  @Get('loans')",
  "  listLoans(@Req() req: any, @Query('status') status?: string) { return this.svc.listLoans(req.user.schoolId, status); }",
  "",
  "  @Post('loans')",
  "  issue(@Req() req: any, @Body() dto: any) { return this.svc.issue(req.user.schoolId, dto); }",
  "",
  "  @Post('loans/:id/return')",
  "  returnLoan(@Param('id') id: string, @Body() body: { fine?: number }) { return this.svc.returnLoan(id, body.fine); }",
  "",
  "  @Post('loans/mark-overdue')",
  "  markOverdue(@Req() req: any) { return this.svc.markOverdue(req.user.schoolId); }",
  "}",
  ""
]));

put('apps/api/src/library/library.module.ts', L([
  "import { Module } from '@nestjs/common';",
  "import { LibraryService } from './library.service';",
  "import { LibraryController } from './library.controller';",
  "",
  "@Module({ providers: [LibraryService], controllers: [LibraryController] })",
  "export class LibraryModule {}",
  ""
]));

console.log('\n✅ Timetable + Library backend written');