import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const root = process.cwd();
const put = (p, c) => {
  const full = join(root, p);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, c, 'utf8');
  console.log('  + ' + p);
};
const L = (a) => a.join('\n');

const receiptSvc = L([
  "import { Injectable, NotFoundException } from '@nestjs/common';",
  "import { existsSync } from 'node:fs';",
  "import { join } from 'node:path';",
  "import { PrismaService } from '../prisma/prisma.service';",
  "import PDFDocument from 'pdfkit';",
  "",
  "const FONT_DIR = join(process.cwd(), 'apps', 'api', 'assets');",
  "const AMIRI_REGULAR = join(FONT_DIR, 'Amiri-Regular.ttf');",
  "const AMIRI_BOLD = join(FONT_DIR, 'Amiri-Bold.ttf');",
  "",
  "function registerFonts(doc: any): boolean {",
  "  if (!existsSync(AMIRI_REGULAR) || !existsSync(AMIRI_BOLD)) return false;",
  "  try { doc.registerFont('Amiri', AMIRI_REGULAR); doc.registerFont('Amiri-Bold', AMIRI_BOLD); return true; } catch { return false; }",
  "}",
  "",
  "function bidi(text: string): string {",
  "  if (!text) return text;",
  "  const re = /[\\u0600-\\u06FF\\u0750-\\u077F\\u08A0-\\u08FF\\uFB50-\\uFDFF\\uFE70-\\uFEFF]+/g;",
  "  const out: string[] = [];",
  "  let last = 0; let m: RegExpExecArray | null;",
  "  while ((m = re.exec(text)) !== null) {",
  "    out.push(text.slice(last, m.index));",
  "    out.push(m[0].split('').reverse().join(''));",
  "    last = m.index + m[0].length;",
  "  }",
  "  out.push(text.slice(last));",
  "  return out.join('');",
  "}",
  "",
  "const TITLES = {",
  "  en: 'PAYMENT RECEIPT',",
  "  fr: 'RECU DE PAIEMENT',",
  "  ar: 'ايصال دفع',",
  "};",
  "",
  "const LABELS = {",
  "  en: {",
  "    receipt: 'Receipt no', date: 'Date',",
  "    student: 'Student', admission: 'Admission no', class: 'Class',",
  "    invoice: 'Invoice', method: 'Payment method', reference: 'Reference',",
  "    invoiceTotal: 'Invoice total',",
  "    paidBefore: 'Previously paid',",
  "    amountNow: 'Amount received',",
  "    balanceAfter: 'Remaining balance',",
  "    totalPaid: 'Total paid on this invoice',",
  "    thankYou: 'Thank you for your payment.',",
  "    signature: 'Signature & Stamp',",
  "    cashier: 'Cashier',",
  "  },",
  "  fr: {",
  "    receipt: 'Recu no', date: 'Date',",
  "    student: 'Eleve', admission: 'Matricule', class: 'Classe',",
  "    invoice: 'Facture', method: 'Moyen de paiement', reference: 'Reference',",
  "    invoiceTotal: 'Total facture',",
  "    paidBefore: 'Deja paye',",
  "    amountNow: 'Montant recu',",
  "    balanceAfter: 'Solde restant',",
  "    totalPaid: 'Total paye sur cette facture',",
  "    thankYou: 'Merci pour votre paiement.',",
  "    signature: 'Signature & Cachet',",
  "    cashier: 'Caissier',",
  "  },",
  "  ar: {",
  "    receipt: 'رقم الإيصال', date: 'التاريخ',",
  "    student: 'الطالب', admission: 'رقم التسجيل', class: 'الفصل',",
  "    invoice: 'الفاتورة', method: 'طريقة الدفع', reference: 'المرجع',",
  "    invoiceTotal: 'إجمالي الفاتورة',",
  "    paidBefore: 'المدفوع سابقاً',",
  "    amountNow: 'المبلغ المستلم',",
  "    balanceAfter: 'الرصيد المتبقي',",
  "    totalPaid: 'إجمالي المدفوع',",
  "    thankYou: 'شكراً لدفعكم.',",
  "    signature: 'التوقيع والخاتم',",
  "    cashier: 'أمين الصندوق',",
  "  },",
  "};",
  "",
  "function loc(v: string): 'en' | 'fr' | 'ar' {",
  "  return v === 'en' || v === 'ar' ? v : 'fr';",
  "}",
  "",
  "function fmtXAF(n: number) {",
  "  return new Intl.NumberFormat('fr-CM', { style: 'currency', currency: 'XAF', maximumFractionDigits: 0 }).format(n);",
  "}",
  "",
  "function methodLabel(m: string): string {",
  "  const map: Record<string, string> = {",
  "    CASH: 'Especes / Cash',",
  "    MTN_MOMO: 'MTN Mobile Money',",
  "    ORANGE_MONEY: 'Orange Money',",
  "    BANK_TRANSFER: 'Virement / Bank transfer',",
  "    MOBILE_MONEY_MTN: 'MTN Mobile Money',",
  "    MOBILE_MONEY_ORANGE: 'Orange Money',",
  "    CHEQUE: 'Cheque',",
  "    CARD: 'Carte / Card',",
  "    OTHER: 'Autre / Other',",
  "  };",
  "  return map[m] || m;",
  "}",
  "",
  "@Injectable()",
  "export class ReceiptService {",
  "  constructor(private prisma: PrismaService) {}",
  "",
  "  async render(paymentId: string, locale = 'fr'): Promise<NodeJS.ReadableStream> {",
  "    const l = loc(locale);",
  "    const TT = TITLES[l];",
  "    const Lb = LABELS[l];",
  "",
  "    const payment = await this.prisma.payment.findUnique({",
  "      where: { id: paymentId },",
  "      include: {",
  "        invoice: { include: { student: { include: { class: true } } } },",
  "      },",
  "    });",
  "    if (!payment) throw new NotFoundException('payment_not_found');",
  "",
  "    const invoice = payment.invoice;",
  "    const student = invoice.student;",
  "    const school = await this.prisma.school.findUnique({ where: { id: invoice.schoolId } });",
  "",
  "    // Compute totals: how much was paid BEFORE this payment, and AFTER",
  "    const allPayments = await this.prisma.payment.findMany({",
  "      where: { invoiceId: invoice.id, status: 'SUCCESS' },",
  "      orderBy: { paidAt: 'asc' },",
  "    });",
  "    let before = 0; let after = 0;",
  "    for (const p of allPayments) {",
  "      if (p.id === payment.id) { before = after; after += p.amount; break; }",
  "      after += p.amount;",
  "      before = after;",
  "    }",
  "    // Recompute properly: sum of payments strictly before this one",
  "    before = 0;",
  "    for (const p of allPayments) {",
  "      if (p.paidAt < payment.paidAt) before += p.amount;",
  "    }",
  "    const totalPaid = before + payment.amount;",
  "    const balanceAfter = Math.max(0, invoice.total - totalPaid);",
  "",
  "    // Receipt number: RCP-{year}-{sequence per school}",
  "    const year = new Date(payment.paidAt).getFullYear();",
  "    const seqCount = await this.prisma.payment.count({",
  "      where: { schoolId: invoice.schoolId, paidAt: { lte: payment.paidAt } },",
  "    });",
  "    const receiptNo = 'RCP-' + year + '-' + String(seqCount).padStart(5, '0');",
  "",
  "    const doc = new PDFDocument({ size: 'A5', margin: 40 });",
  "    const hasArabic = registerFonts(doc);",
  "    const isAr = l === 'ar' && hasArabic;",
  "    const fontName = isAr ? 'Amiri' : 'Helvetica';",
  "    const fontBold = isAr ? 'Amiri-Bold' : 'Helvetica-Bold';",
  "    const tr = (s: string) => (isAr ? bidi(s) : s);",
  "",
  "    // Header",
  "    doc.font(fontBold).fontSize(16).text(tr(school?.name ?? 'School'), { align: 'center' });",
  "    if (school?.email) doc.font(fontName).fontSize(8).fillColor('#666').text(school.email, { align: 'center' });",
  "    doc.moveDown(0.5);",
  "    doc.fillColor('#000').font(fontBold).fontSize(13).text(tr(TT), { align: 'center' });",
  "    doc.moveDown(0.8);",
  "",
  "    // Receipt number + date box",
  "    const topY = doc.y;",
  "    doc.font(fontName).fontSize(9);",
  "    doc.text(tr(Lb.receipt) + ': ' + receiptNo, 40, topY);",
  "    doc.text(tr(Lb.date) + ': ' + new Date(payment.paidAt).toLocaleString(), 40, topY + 14);",
  "    doc.moveTo(40, topY + 32).lineTo(555, topY + 32).stroke('#0f766e');",
  "    doc.y = topY + 44;",
  "",
  "    // Student block",
  "    const sY = doc.y;",
  "    doc.font(fontName).fontSize(10);",
  "    doc.text(tr(student.firstName + ' ' + student.lastName), 40, sY);",
  "    doc.fontSize(9).fillColor('#555');",
  "    doc.text(tr(Lb.admission) + ': ' + student.admissionNo, 40, sY + 16);",
  "    doc.text(tr(Lb.class) + ': ' + tr(student.class?.name ?? '-'), 40, sY + 30);",
  "    doc.text(tr(Lb.invoice) + ': ' + invoice.invoiceNo, 40, sY + 44);",
  "    doc.fillColor('#000');",
  "    doc.y = sY + 62;",
  "",
  "    // Amounts table",
  "    const rowH = 22;",
  "    const startX = 40;",
  "    let y = doc.y;",
  "",
  "    const row = (label: string, value: string, bold = false) => {",
  "      doc.rect(startX, y, 515, rowH).stroke('#e5e7eb');",
  "      doc.font(bold ? fontBold : fontName).fontSize(10);",
  "      doc.text(tr(label), startX + 8, y + 6);",
  "      doc.text(value, 0, y + 6, { width: 555 - 8, align: 'right' });",
  "      y += rowH;",
  "    };",
  "",
  "    // Header row",
  "    doc.rect(startX, y, 515, rowH).fill('#0f766e');",
  "    doc.fillColor('#fff').font(fontBold).fontSize(10);",
  "    doc.text(tr(Lb.amountNow), startX + 8, y + 6);",
  "    doc.text(fmtXAF(payment.amount), 0, y + 6, { width: 555 - 8, align: 'right' });",
  "    doc.fillColor('#000');",
  "    y += rowH;",
  "",
  "    row(Lb.invoiceTotal, fmtXAF(invoice.total));",
  "    row(Lb.paidBefore, fmtXAF(before));",
  "    row(Lb.totalPaid, fmtXAF(totalPaid), true);",
  "    row(Lb.balanceAfter, fmtXAF(balanceAfter), true);",
  "",
  "    doc.y = y + 12;",
  "",
  "    // Payment method block",
  "    doc.font(fontName).fontSize(9);",
  "    doc.text(tr(Lb.method) + ': ' + methodLabel(payment.method), 40, doc.y);",
  "    if (payment.reference) doc.text(tr(Lb.reference) + ': ' + payment.reference, 40, doc.y + 14);",
  "    doc.moveDown(3);",
  "",
  "    // Footer",
  "    const fY = doc.y;",
  "    doc.font(fontName).fontSize(9).fillColor('#555').text(tr(Lb.cashier) + ':', 40, fY + 20);",
  "    doc.moveTo(40, fY + 46).lineTo(200, fY + 46).stroke();",
  "    doc.text(tr(Lb.signature) + ':', 350, fY + 20);",
  "    doc.moveTo(350, fY + 46).lineTo(500, fY + 46).stroke();",
  "    doc.fontSize(8).fillColor('#999').text(tr(Lb.thankYou), 40, fY + 80, { align: 'center', width: 515 });",
  "",
  "    doc.end();",
  "    return doc;",
  "  }",
  "}",
  ""
]);

put('apps/api/src/payments/receipt.service.ts', receiptSvc);

// Patch the PaymentsModule to include the service
put('apps/api/src/payments/payments.module.ts', L([
  "import { Module } from '@nestjs/common';",
  "import { CinetPayService } from './cinetpay.service';",
  "import { PaymentsController } from './payments.controller';",
  "import { ReceiptService } from './receipt.service';",
  "",
  "@Module({",
  "  providers: [CinetPayService, ReceiptService],",
  "  controllers: [PaymentsController],",
  "})",
  "export class PaymentsModule {}",
  ""
]));

// Patch the controller to add the receipt route
put('apps/api/src/payments/payments.controller.ts', L([
  "import { Body, Controller, Get, Param, Post, Query, Req, Res, UseGuards } from '@nestjs/common';",
  "import { Response } from 'express';",
  "import { CinetPayService } from './cinetpay.service';",
  "import { ReceiptService } from './receipt.service';",
  "import { JwtAuthGuard } from '../common/guards/jwt-auth.guard';",
  "",
  "@Controller('payments')",
  "export class PaymentsController {",
  "  constructor(",
  "    private cinetpay: CinetPayService,",
  "    private receipts: ReceiptService,",
  "  ) {}",
  "",
  "  @UseGuards(JwtAuthGuard)",
  "  @Post('cinetpay/init/:invoiceId')",
  "  init(@Param('invoiceId') invoiceId: string) {",
  "    return this.cinetpay.initializeForInvoice(invoiceId);",
  "  }",
  "",
  "  @UseGuards(JwtAuthGuard)",
  "  @Get('cinetpay/verify/:txId')",
  "  verify(@Param('txId') txId: string) {",
  "    return this.cinetpay.verifyTransaction(txId);",
  "  }",
  "",
  "  @Post('cinetpay/webhook')",
  "  webhook(@Body() body: any) {",
  "    return this.cinetpay.handleWebhook(body);",
  "  }",
  "",
  "  @UseGuards(JwtAuthGuard)",
  "  @Get(':id/receipt')",
  "  async receipt(",
  "    @Param('id') id: string,",
  "    @Query('locale') locale: string,",
  "    @Res() res: Response,",
  "  ) {",
  "    const stream = await this.receipts.render(id, locale || 'fr');",
  "    res.setHeader('Content-Type', 'application/pdf');",
  "    res.setHeader('Content-Disposition', 'attachment; filename=\"receipt-' + id + '.pdf\"');",
  "    stream.pipe(res);",
  "  }",
  "}",
  ""
]));

console.log('\\n✅ Receipt backend written');