import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const root = process.cwd();
const put = (p, c) => {
  const full = join(root, p);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, c, 'utf8');
  console.log('  + ' + p);
};
const L = (a) => a.join('\n');

// ---------- Grades ----------
put('apps/web/app/[locale]/student/grades/page.tsx', L([
  "'use client';",
  "import { useEffect, useState } from 'react';",
  "import { useParams } from 'next/navigation';",
  "import { apiFetch } from '@/lib/api';",
  "",
  "export default function StudentGrades() {",
  "  const { locale } = useParams() as { locale: string };",
  "  const l = locale === 'en' || locale === 'ar' ? locale : 'fr';",
  "  const [data, setData] = useState<any>(null);",
  "  const [err, setErr] = useState<string | null>(null);",
  "",
  "  const T = {",
  "    title:   { en: 'My grades', fr: 'Mes notes', ar: 'علاماتي' },",
  "    subject: { en: 'Subject', fr: 'Matiere', ar: 'المادة' },",
  "    score:   { en: 'Score', fr: 'Note', ar: 'العلامة' },",
  "    coef:    { en: 'Coef', fr: 'Coef', ar: 'المعامل' },",
  "    average: { en: 'Average', fr: 'Moyenne', ar: 'المعدل' },",
  "    rank:    { en: 'Rank', fr: 'Rang', ar: 'الترتيب' },",
  "    noData:  { en: 'No grades yet.', fr: 'Aucune note.', ar: 'لا توجد علامات.' },",
  "    loading: { en: 'Loading…', fr: 'Chargement…', ar: 'جار التحميل…' },",
  "  };",
  "",
  "  useEffect(() => {",
  "    apiFetch('/api/v1/student/grades')",
  "      .then((r) => (r.ok ? r.json() : Promise.reject(r.status)))",
  "      .then(setData)",
  "      .catch((e) => setErr(String(e)));",
  "  }, []);",
  "",
  "  return (",
  "    <div>",
  "      <h1 className=\"text-2xl font-bold\">{T.title[l]}</h1>",
  "      {err && <p className=\"mt-4 text-red-600\">{err}</p>}",
  "      {!data && !err && <p className=\"mt-4 text-gray-500\">{T.loading[l]}</p>}",
  "      {data && data.exams.length === 0 && <p className=\"mt-4 text-gray-500\">{T.noData[l]}</p>}",
  "      <div className=\"mt-6 space-y-6\">",
  "        {data?.exams.map((e: any) => (",
  "          <div key={e.exam.id} className=\"rounded-xl border bg-white p-5\">",
  "            <div className=\"flex flex-wrap items-center justify-between gap-2\">",
  "              <div>",
  "                <div className=\"font-semibold\">{e.exam.name}</div>",
  "                <div className=\"text-xs text-gray-500\">{e.exam.type} · {new Date(e.exam.startDate).toLocaleDateString()}</div>",
  "              </div>",
  "              <div className=\"flex gap-2\">",
  "                {e.average !== null && (",
  "                  <span className=\"rounded-lg bg-teal-50 px-3 py-1 text-sm font-bold text-teal-800\">",
  "                    {T.average[l]}: {e.average.toFixed(2)} / 20",
  "                  </span>",
  "                )}",
  "                {e.rank && (",
  "                  <span className=\"rounded-lg bg-violet-50 px-3 py-1 text-sm font-bold text-violet-800\">",
  "                    {T.rank[l]}: #{e.rank}/{e.classSize}",
  "                  </span>",
  "                )}",
  "              </div>",
  "            </div>",
  "            <table className=\"mt-4 w-full border-collapse text-sm\">",
  "              <thead className=\"bg-gray-50 text-left\">",
  "                <tr>",
  "                  <th className=\"p-2 font-medium\">{T.subject[l]}</th>",
  "                  <th className=\"p-2 text-center font-medium\">{T.coef[l]}</th>",
  "                  <th className=\"p-2 text-right font-medium\">{T.score[l]}</th>",
  "                </tr>",
  "              </thead>",
  "              <tbody>",
  "                {e.marks.map((m: any, i: number) => (",
  "                  <tr key={i} className=\"border-t\">",
  "                    <td className=\"p-2\">{m.subject} <span className=\"text-xs text-gray-400\">({m.code})</span></td>",
  "                    <td className=\"p-2 text-center\">{m.coefficient}</td>",
  "                    <td className=\"p-2 text-right font-medium\">{m.score} / {m.maxScore}</td>",
  "                  </tr>",
  "                ))}",
  "              </tbody>",
  "            </table>",
  "          </div>",
  "        ))}",
  "      </div>",
  "    </div>",
  "  );",
  "}",
  ""
]));

// ---------- Invoices ----------
put('apps/web/app/[locale]/student/invoices/page.tsx', L([
  "'use client';",
  "import { useEffect, useState } from 'react';",
  "import { useParams } from 'next/navigation';",
  "import { apiFetch } from '@/lib/api';",
  "import { formatXAF } from '@/lib/format';",
  "",
  "export default function StudentInvoices() {",
  "  const { locale } = useParams() as { locale: string };",
  "  const l = locale === 'en' || locale === 'ar' ? locale : 'fr';",
  "  const [data, setData] = useState<any>(null);",
  "  const [err, setErr] = useState<string | null>(null);",
  "",
  "  const T = {",
  "    title:   { en: 'My invoices', fr: 'Mes factures', ar: 'فواتيري' },",
  "    billed:  { en: 'Billed', fr: 'Facture', ar: 'المفوتر' },",
  "    paid:    { en: 'Paid', fr: 'Paye', ar: 'المدفوع' },",
  "    balance: { en: 'Balance', fr: 'Solde', ar: 'الرصيد' },",
  "    number:  { en: 'Number', fr: 'Numero', ar: 'الرقم' },",
  "    due:     { en: 'Due', fr: 'Echeance', ar: 'الاستحقاق' },",
  "    total:   { en: 'Total', fr: 'Total', ar: 'الاجمالي' },",
  "    status:  { en: 'Status', fr: 'Statut', ar: 'الحالة' },",
  "    empty:   { en: 'No invoices.', fr: 'Aucune facture.', ar: 'لا توجد فواتير.' },",
  "    loading: { en: 'Loading…', fr: 'Chargement…', ar: 'جار التحميل…' },",
  "    hint:    { en: 'Ask your parents to pay via the parent portal.', fr: 'Demandez a vos parents de payer via le portail parent.', ar: 'اطلب من والديك الدفع عبر بوابة الوالدين.' },",
  "  };",
  "",
  "  useEffect(() => {",
  "    apiFetch('/api/v1/student/invoices')",
  "      .then((r) => (r.ok ? r.json() : Promise.reject(r.status)))",
  "      .then(setData)",
  "      .catch((e) => setErr(String(e)));",
  "  }, []);",
  "",
  "  return (",
  "    <div>",
  "      <h1 className=\"text-2xl font-bold\">{T.title[l]}</h1>",
  "      {err && <p className=\"mt-4 text-red-600\">{err}</p>}",
  "      {!data && !err && <p className=\"mt-4 text-gray-500\">{T.loading[l]}</p>}",
  "      {data && (",
  "        <>",
  "          <div className=\"mt-6 grid grid-cols-1 gap-4 sm:grid-cols-3\">",
  "            <div className=\"rounded-xl border bg-teal-50 p-4\">",
  "              <div className=\"text-xs uppercase text-teal-800 opacity-70\">{T.billed[l]}</div>",
  "              <div className=\"mt-1 text-2xl font-bold text-teal-900\">{formatXAF(data.summary.totalBilled)}</div>",
  "            </div>",
  "            <div className=\"rounded-xl border bg-green-50 p-4\">",
  "              <div className=\"text-xs uppercase text-green-800 opacity-70\">{T.paid[l]}</div>",
  "              <div className=\"mt-1 text-2xl font-bold text-green-900\">{formatXAF(data.summary.totalPaid)}</div>",
  "            </div>",
  "            <div className=\"rounded-xl border bg-red-50 p-4\">",
  "              <div className=\"text-xs uppercase text-red-800 opacity-70\">{T.balance[l]}</div>",
  "              <div className=\"mt-1 text-2xl font-bold text-red-900\">{formatXAF(data.summary.balance)}</div>",
  "            </div>",
  "          </div>",
  "          <div className=\"mt-6 overflow-x-auto rounded-lg border\">",
  "            <table className=\"w-full border-collapse text-sm\">",
  "              <thead className=\"bg-gray-50 text-left\">",
  "                <tr>",
  "                  <th className=\"p-3 font-medium\">{T.number[l]}</th>",
  "                  <th className=\"p-3 font-medium\">{T.due[l]}</th>",
  "                  <th className=\"p-3 text-right font-medium\">{T.total[l]}</th>",
  "                  <th className=\"p-3 text-right font-medium\">{T.paid[l]}</th>",
  "                  <th className=\"p-3 text-right font-medium\">{T.balance[l]}</th>",
  "                  <th className=\"p-3 font-medium\">{T.status[l]}</th>",
  "                </tr>",
  "              </thead>",
  "              <tbody>",
  "                {data.invoices.length === 0 && (",
  "                  <tr><td colSpan={6} className=\"p-6 text-center text-gray-500\">{T.empty[l]}</td></tr>",
  "                )}",
  "                {data.invoices.map((i: any) => (",
  "                  <tr key={i.id} className=\"border-t\">",
  "                    <td className=\"p-3 font-mono text-xs\">{i.invoiceNo}</td>",
  "                    <td className=\"p-3 text-xs\">{new Date(i.dueDate).toLocaleDateString()}</td>",
  "                    <td className=\"p-3 text-right\">{formatXAF(i.total)}</td>",
  "                    <td className=\"p-3 text-right text-green-700\">{formatXAF(i.amountPaid)}</td>",
  "                    <td className=\"p-3 text-right font-medium\">{formatXAF(i.balance)}</td>",
  "                    <td className=\"p-3\">",
  "                      <span className={'rounded-full px-2 py-0.5 text-xs font-medium ' +",
  "                        (i.status === 'PAID' ? 'bg-green-100 text-green-800' :",
  "                         i.status === 'PARTIAL' ? 'bg-yellow-100 text-yellow-800' : 'bg-red-100 text-red-800')}>",
  "                        {i.status}",
  "                      </span>",
  "                    </td>",
  "                  </tr>",
  "                ))}",
  "              </tbody>",
  "            </table>",
  "          </div>",
  "          <p className=\"mt-3 text-xs text-gray-500\">{T.hint[l]}</p>",
  "        </>",
  "      )}",
  "    </div>",
  "  );",
  "}",
  ""
]));

// ---------- Attendance ----------
put('apps/web/app/[locale]/student/attendance/page.tsx', L([
  "'use client';",
  "import { useEffect, useState } from 'react';",
  "import { useParams } from 'next/navigation';",
  "import { apiFetch } from '@/lib/api';",
  "",
  "export default function StudentAttendance() {",
  "  const { locale } = useParams() as { locale: string };",
  "  const l = locale === 'en' || locale === 'ar' ? locale : 'fr';",
  "  const [data, setData] = useState<any>(null);",
  "  const [err, setErr] = useState<string | null>(null);",
  "",
  "  const T = {",
  "    title:   { en: 'My attendance', fr: 'Ma presence', ar: 'حضوري' },",
  "    present: { en: 'Present', fr: 'Presents', ar: 'حاضر' },",
  "    absent:  { en: 'Absent', fr: 'Absents', ar: 'غائب' },",
  "    late:    { en: 'Late', fr: 'Retards', ar: 'متأخر' },",
  "    excused: { en: 'Excused', fr: 'Excuses', ar: 'بعذر' },",
  "    rate:    { en: 'Rate', fr: 'Taux', ar: 'النسبة' },",
  "    recent:  { en: 'Recent records', fr: 'Enregistrements recents', ar: 'السجلات الأخيرة' },",
  "    date:    { en: 'Date', fr: 'Date', ar: 'التاريخ' },",
  "    status:  { en: 'Status', fr: 'Statut', ar: 'الحالة' },",
  "    loading: { en: 'Loading…', fr: 'Chargement…', ar: 'جار التحميل…' },",
  "  };",
  "",
  "  useEffect(() => {",
  "    apiFetch('/api/v1/student/attendance')",
  "      .then((r) => (r.ok ? r.json() : Promise.reject(r.status)))",
  "      .then(setData)",
  "      .catch((e) => setErr(String(e)));",
  "  }, []);",
  "",
  "  return (",
  "    <div>",
  "      <h1 className=\"text-2xl font-bold\">{T.title[l]}</h1>",
  "      {err && <p className=\"mt-4 text-red-600\">{err}</p>}",
  "      {!data && !err && <p className=\"mt-4 text-gray-500\">{T.loading[l]}</p>}",
  "      {data && (",
  "        <>",
  "          <div className=\"mt-6 grid grid-cols-2 gap-3 sm:grid-cols-5\">",
  "            <Stat label={T.present[l]} value={data.summary.PRESENT} tone=\"green\" />",
  "            <Stat label={T.absent[l]} value={data.summary.ABSENT} tone=\"red\" />",
  "            <Stat label={T.late[l]} value={data.summary.LATE} tone=\"amber\" />",
  "            <Stat label={T.excused[l]} value={data.summary.EXCUSED} tone=\"blue\" />",
  "            <Stat label={T.rate[l]} value={data.summary.rate + '%'} tone=\"brand\" />",
  "          </div>",
  "          <h3 className=\"mt-6 text-sm font-semibold\">{T.recent[l]}</h3>",
  "          <div className=\"mt-2 max-h-96 overflow-y-auto rounded-lg border\">",
  "            <table className=\"w-full border-collapse text-sm\">",
  "              <thead className=\"sticky top-0 bg-gray-50 text-left\">",
  "                <tr>",
  "                  <th className=\"p-2 font-medium\">{T.date[l]}</th>",
  "                  <th className=\"p-2 font-medium\">{T.status[l]}</th>",
  "                </tr>",
  "              </thead>",
  "              <tbody>",
  "                {data.recent.length === 0 && (",
  "                  <tr><td colSpan={2} className=\"p-4 text-center text-gray-500\">—</td></tr>",
  "                )}",
  "                {data.recent.map((r: any, i: number) => (",
  "                  <tr key={i} className=\"border-t\">",
  "                    <td className=\"p-2 text-xs\">{new Date(r.date).toLocaleDateString()}</td>",
  "                    <td className=\"p-2\">",
  "                      <span className={'rounded-full px-2 py-0.5 text-xs font-medium ' +",
  "                        (r.status === 'PRESENT' ? 'bg-green-100 text-green-800' :",
  "                         r.status === 'ABSENT' ? 'bg-red-100 text-red-800' :",
  "                         r.status === 'LATE' ? 'bg-yellow-100 text-yellow-800' : 'bg-blue-100 text-blue-800')}>",
  "                        {r.status}",
  "                      </span>",
  "                    </td>",
  "                  </tr>",
  "                ))}",
  "              </tbody>",
  "            </table>",
  "          </div>",
  "        </>",
  "      )}",
  "    </div>",
  "  );",
  "}",
  "",
  "function Stat({ label, value, tone }: { label: string; value: number | string; tone: 'green'|'red'|'amber'|'blue'|'brand' }) {",
  "  const colors: Record<string, string> = {",
  "    green: 'border-green-200 bg-green-50 text-green-900',",
  "    red:   'border-red-200 bg-red-50 text-red-900',",
  "    amber: 'border-amber-200 bg-amber-50 text-amber-900',",
  "    blue:  'border-blue-200 bg-blue-50 text-blue-900',",
  "    brand: 'border-teal-200 bg-teal-50 text-teal-900',",
  "  };",
  "  return (",
  "    <div className={'rounded-xl border p-3 ' + colors[tone]}>",
  "      <div className=\"text-[10px] uppercase tracking-wide opacity-70\">{label}</div>",
  "      <div className=\"mt-1 text-xl font-bold\">{value}</div>",
  "    </div>",
  "  );",
  "}",
  ""
]));

// ---------- Announcements ----------
put('apps/web/app/[locale]/student/announcements/page.tsx', L([
  "'use client';",
  "import { useEffect, useState } from 'react';",
  "import { useParams } from 'next/navigation';",
  "import { apiFetch } from '@/lib/api';",
  "",
  "export default function StudentAnnouncements() {",
  "  const { locale } = useParams() as { locale: string };",
  "  const l = locale === 'en' || locale === 'ar' ? locale : 'fr';",
  "  const [rows, setRows] = useState<any[]>([]);",
  "  const [err, setErr] = useState<string | null>(null);",
  "",
  "  const T = {",
  "    title:   { en: 'Announcements', fr: 'Annonces', ar: 'الإعلانات' },",
  "    empty:   { en: 'No announcements.', fr: 'Aucune annonce.', ar: 'لا توجد إعلانات.' },",
  "    loading: { en: 'Loading…', fr: 'Chargement…', ar: 'جار التحميل…' },",
  "  };",
  "",
  "  useEffect(() => {",
  "    apiFetch('/api/v1/student/announcements')",
  "      .then((r) => (r.ok ? r.json() : []))",
  "      .then((d) => setRows(Array.isArray(d) ? d : []))",
  "      .catch((e) => setErr(String(e)));",
  "  }, []);",
  "",
  "  return (",
  "    <div>",
  "      <h1 className=\"text-2xl font-bold\">{T.title[l]}</h1>",
  "      {err && <p className=\"mt-4 text-red-600\">{err}</p>}",
  "      {!err && rows.length === 0 && <p className=\"mt-4 text-gray-500\">{T.loading[l]}</p>}",
  "      <div className=\"mt-6 space-y-3\">",
  "        {rows.map((a) => (",
  "          <div key={a.id} className=\"rounded-xl border bg-white p-5\">",
  "            <div className=\"font-semibold\">{a.title}</div>",
  "            <div className=\"mt-1 text-xs text-gray-500\">",
  "              {a.publishedAt ? new Date(a.publishedAt).toLocaleString() : ''}",
  "            </div>",
  "            <p className=\"mt-3 whitespace-pre-wrap text-sm text-gray-700\">{a.body}</p>",
  "          </div>",
  "        ))}",
  "      </div>",
  "    </div>",
  "  );",
  "}",
  ""
]));

// ---------- Login redirect ----------
const loginPath = join(root, 'apps/web/app/[locale]/login/page.tsx');
let login = readFileSync(loginPath, 'utf8');

if (login.includes("'/student'")) {
  console.log('  = login already redirects STUDENT');
} else {
  const before = "const target = data.user.role === 'PARENT' ? '/parent' : '/dashboard';";
  const after  = "const role = data.user.role;\n      const target = role === 'PARENT' ? '/parent' : role === 'STUDENT' ? '/student' : '/dashboard';";
  if (login.includes(before)) {
    login = login.replace(before, after);
    writeFileSync(loginPath, login, 'utf8');
    console.log('  + login page — STUDENT redirect added');
  } else {
    console.log('  ! login redirect anchor not found — check manually');
  }
}

console.log('\n✅ Student UI complete');
console.log('  6 pages + login redirect');